(()=>{'use strict';
const KEY='srpskilab_progress_v1';
const LEVELS={A0:{title:'С самого начала',subtitle:'Алфавит и первые диалоги',tone:'#6f8e79'},A1:{title:'Базовое общение',subtitle:'Семья, город, еда и дом',tone:'#4a8f92'},A2:{title:'Жизнь в Сербии',subtitle:'Падежи, документы и телефон',tone:'#5c8bad'},B1:{title:'Самостоятельная речь',subtitle:'Работа, планы и аргументы',tone:'#9275b8'},B2:{title:'Уверенная коммуникация',subtitle:'Дискуссии и профессиональный язык',tone:'#e2a45e'}};
const modules=window.SR_MODULES||[];
let seq=0;const lessons=modules.flatMap(m=>m.lessons.map((l,i)=>({...l,id:`m${m.id}l${i+1}`,num:++seq,chapter:i+1,module:m,level:m.level})));
const byLesson=Object.fromEntries(lessons.map(l=>[l.id,l]));
const state=loadState();
const ui={navOpen:false,level:'all',search:'',dictSearch:'',dictLevel:'all',dictMode:'all',quiz:null,dialogTranslations:false,flashFlip:false,examLevel:'A0',toast:'',showMoreWords:false};
const $=(s,root=document)=>root.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=s=>encodeURIComponent(s);
function blankState(){return {version:1,name:'Кирилл',theme:'light',script:'latin',goal:1,lessons:{},exams:{},seen:{},reviews:{},events:{},errors:[],settings:{}};}
function loadState(){try {const o=JSON.parse(localStorage.getItem(KEY)||'null');if(!o||typeof o!=='object'||o.version!==1)return blankState();return {...blankState(),...o,lessons:o.lessons||{},exams:o.exams||{},seen:o.seen||{},reviews:o.reviews||{},events:o.events||{},errors:Array.isArray(o.errors)?o.errors.slice(-120):[]};}catch{return blankState();}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('Хранилище браузера переполнено. Экспортируй прогресс.');}}
function today(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
function track(type){const key=today();state.events[key]??={lessons:0,reviews:0,tests:0};state.events[key][type]=(state.events[key][type]||0)+1;save();}
function streak(){let d=new Date(),n=0; if(!state.events[today(d)])d.setDate(d.getDate()-1);while(state.events[today(d)]){n++;d.setDate(d.getDate()-1);}return n;}
function totalDone(){return lessons.filter(l=>state.lessons[l.id]?.done).length;}
function modDone(m){return m.lessons.filter((_,i)=>state.lessons[`m${m.id}l${i+1}`]?.done).length;}
function levelDone(level){return lessons.filter(l=>l.level===level&&state.lessons[l.id]?.done).length;}
function levelTotal(level){return lessons.filter(l=>l.level===level).length;}
function nextLesson(){return lessons.find(l=>!state.lessons[l.id]?.done)||lessons[lessons.length-1];}
function percent(x,y){return Math.round(x/Math.max(1,y)*100);}
function romanToCyr(text){const multi={'dž':'џ','lj':'љ','nj':'њ'};const single={'a':'а','b':'б','c':'ц','č':'ч','ć':'ћ','d':'д','đ':'ђ','e':'е','f':'ф','g':'г','h':'х','i':'и','j':'ј','k':'к','l':'л','m':'м','n':'н','o':'о','p':'п','r':'р','s':'с','š':'ш','t':'т','u':'у','v':'в','z':'з','ž':'ж'};return String(text).replace(/dž|lj|nj|[a-zčćđšž]/gi,token=>{const low=token.toLowerCase(),v=multi[low]||single[low]||token;return token[0]===token[0].toUpperCase()?v.toUpperCase():v;});}
function cyrToRoman(text){const m={'а':'a','б':'b','в':'v','г':'g','д':'d','ђ':'đ','е':'e','ж':'ž','з':'z','и':'i','ј':'j','к':'k','л':'l','љ':'lj','м':'m','н':'n','њ':'nj','о':'o','п':'p','р':'r','с':'s','т':'t','ћ':'ć','у':'u','ф':'f','х':'h','ц':'c','ч':'č','џ':'dž','ш':'š'};return String(text).replace(/[а-шђјљњћџ]/gi,c=>{let v=m[c.toLowerCase()]||c;return c===c.toUpperCase()?v[0].toUpperCase()+v.slice(1):v;});}
function sr(s){return state.script==='cyrillic'?romanToCyr(s):s;}
function wordId(s){return cyrToRoman(s).toLowerCase().trim();}
function norm(s){return cyrToRoman(s).toLocaleLowerCase('sr').normalize('NFKC').replace(/[!?.,:;„“«»"'–—()]/g,'').replace(/\s+/g,' ').trim();}
function wordsFor(l){const a=l.module.vocab,start=(l.chapter-1)*3;return Array.from({length:Math.min(11,a.length)},(_,i)=>a[(start+i)%a.length]);}
function sample(arr,seed){return arr[Math.abs(seed)%arr.length];}
function stableShuffle(arr,seed){return [...arr].sort((a,b)=>((hash(String(a)+seed)%100000)-(hash(String(b)+seed)%100000)));}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function wordBank(){const dict=new Map();for(const m of modules)for(const w of m.vocab){const k=wordId(w.sr);if(!dict.has(k))dict.set(k,{...w,key:k,level:m.level,module:m});else if(!dict.get(k).usage&&w.usage)dict.get(k).usage=w.usage;}return [...dict.values()];}
const dictionary=wordBank();const dictMap=new Map(dictionary.map(w=>[w.key,w]));
function lessonMarkSeen(l){for(const w of wordsFor(l)){const k=wordId(w.sr);if(!state.seen[k])state.seen[k]={date:today(),lesson:l.id};}save();}
function numberKnown(){return Object.values(state.reviews).filter(r=>r.stage>=3).length;}
function dueWords(){return dictionary.filter(w=>state.seen[w.key]&&(!state.reviews[w.key]||state.reviews[w.key].due<=Date.now())).sort((a,b)=>(state.reviews[a.key]?.due||0)-(state.reviews[b.key]?.due||0));}
function seenCount(){return Object.keys(state.seen).length;}
function logError(q,typed){state.errors.push({date:today(),display:q.display,prompt:q.prompt,expected:q.answer,typed:String(typed).slice(0,200)});state.errors=state.errors.slice(-120);save();}
function icon(name,size=20){const d={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V3H6.5A2.5 2.5 0 0 0 4 5.5z"/><path d="M4 19.5A2.5 2.5 0 0 0 6.5 22H20"/>',cards:'<rect x="4" y="5" width="14" height="15" rx="2"/><path d="M8 9h6M8 13h6M12 2h6a2 2 0 0 1 2 2v14"/>',flame:'<path d="M12 22c4.4 0 7-3 7-7 0-4-3-7-4-8 .5 4-2 5-3 5 .5-5-3-8-5-9 1 4-2 6-2 11 0 5 3 8 7 8Z"/>',chart:'<path d="M3 3v18h18M7 17v-5M12 17V7M17 17V9"/>',award:'<circle cx="12" cy="8" r="5"/><path d="m8.5 12.5-2 9 5.5-3 5.5 3-2-9"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.89l.06.06-2.12 2.12-.06-.06A1.7 1.7 0 0 0 15.73 19l-.08.04A1.7 1.7 0 0 0 14.6 20.6V21H9.4v-.4a1.7 1.7 0 0 0-1.05-1.56L8.27 19a1.7 1.7 0 0 0-1.89.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 4.6 15.3l-.04-.08A1.7 1.7 0 0 0 3 14.2h-.4V9h.4a1.7 1.7 0 0 0 1.56-1.05l.04-.08A1.7 1.7 0 0 0 4.26 6l-.06-.06L6.32 3.8l.06.06A1.7 1.7 0 0 0 8.27 4.2l.08-.04A1.7 1.7 0 0 0 9.4 2.6V2h5.2v.6a1.7 1.7 0 0 0 1.05 1.56l.08.04a1.7 1.7 0 0 0 1.89-.34l.06-.06 2.12 2.12-.06.06A1.7 1.7 0 0 0 19.4 7.9l.04.08A1.7 1.7 0 0 0 21 9h.4v5.2H21a1.7 1.7 0 0 0-1.56 1.05z"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',back:'<path d="M19 12H5m6-6-6 6 6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',play:'<path d="m8 5 11 7-11 7z"/>',volume:'<path d="M11 5 6 9H3v6h3l5 4zM15 9a4 4 0 0 1 0 6M18 6a8 8 0 0 1 0 12"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',close:'<path d="M5 5 19 19M19 5 5 19"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/>',upload:'<path d="M12 16V4m-4 4 4-4 4 4M4 18v3h16v-3"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 3"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/>',moon:'<path d="M20.5 14.5A8 8 0 0 1 9.5 3.5 8.5 8.5 0 1 0 20.5 14.5Z"/>',bolt:'<path d="m13 2-9 12h7l-1 8 10-12h-7z"/>',translate:'<path d="m5 8 6 6m-7 0 7-7 2-2H3m6-3v3m4 15 5-11 5 11m-8-4h6"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',chat:'<path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9 9 0 0 1-4-.9L3 21l1.9-5a9 9 0 0 1-.9-4 8.4 8.4 0 0 1 8.5-9H13a8.4 8.4 0 0 1 8 8.5Z"/>',spark:'<path d="m12 3 1.8 6.2L20 11l-6.2 1.8L12 19l-1.8-6.2L4 11l6.2-1.8zM20 17l.5 1.5L22 19l-1.5.5L20 21l-.5-1.5L18 19l1.5-.5z"/>',chev:'<path d="m6 9 6 6 6-6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.5"/>'}[name]||d.book;return `<svg aria-hidden="true" class="ic" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;}
const link=(route,text,klass='')=>`<a href="#/${route}" class="${klass}">${text}</a>`;
function actionButton(key,label,variant='secondary',extra=''){return `<button type="button" class="btn ${variant}" data-action="${key}" ${extra}>${label}</button>`;}
function bar(n,d,extra=''){return `<div class="progress-track ${extra}"><div class="progress-fill" style="width:${percent(n,d)}%"></div></div>`;}
function logo(){return `<div class="mark"><span>Ћ</span><span class="mark-dot"></span></div>`;}
function navItem(route,ico,label,current,badge=''){return `<a href="#/${route}" class="nav-link ${current===route||current.startsWith(route+'/')||current.startsWith(route+'?')?'active':''}">${icon(ico,19)}<span>${label}</span>${badge?`<em>${badge}</em>`:''}</a>`;}
function route(){return decodeURIComponent(location.hash.replace(/^#\/?/,'')||'home');}
function shell(content){const r=route(),section=r.split('/')[0].split('?')[0],n=nextLesson();document.documentElement.dataset.theme=state.theme;document.title=(r==='home'?'Главная':({course:'Курс',dictionary:'Словарь',review:'Повторение',exams:'Экзамены',progress:'Прогресс',settings:'Настройки',lesson:'Урок',module:'Модуль'}[section]||'SrpskiLab'))+' · SrpskiLab';return `<div class="app-layout">
<aside class="sidebar ${ui.navOpen?'open':''}" aria-label="Основная навигация"><div class="brand">${logo()}<span>Srpski<span class="brand-accent">Lab</span><small>учим сербский по-настоящему</small></span></div>
<div class="sidebar-kicker">ОБУЧЕНИЕ</div><nav class="nav-menu">${navItem('home','home','Главная',r)}${navItem('course','book','Все уроки',r)}${navItem('dictionary','cards','Словарь',r)}${navItem('review','bolt','Повторение',r,dueWords().length||'')}${navItem('exams','award','Экзамены',r)}</nav>
<div class="sidebar-kicker side-section">ТВОЙ КАБИНЕТ</div><nav class="nav-menu">${navItem('progress','chart','Мой прогресс',r)}${navItem('settings','settings','Настройки',r)}</nav>
<div class="side-bottom"><div class="side-learning"><div class="side-ring">${Math.min(99,percent(totalDone(),265))}%</div><div><strong>Большая цель — B2</strong><small>${totalDone()} из 265 уроков</small>${bar(totalDone(),265)}</div></div><div class="side-bottom-caption">Сделано с заботой о тех, кто живёт в Сербии 🇷🇸</div></div></aside>
${ui.navOpen?'<button class="mobile-scrim" data-action="toggle-menu" aria-label="Закрыть меню"></button>':''}
<div class="main-column"><header class="topbar"><div class="topbar-left"><button class="icon-btn mobile-only" data-action="toggle-menu" aria-label="Меню">${icon('menu',22)}</button><div class="breadcrumbs">${link('home','Главная')}<span>/</span><strong>${r==='home'?'Обзор':section==='lesson'?'Урок':section==='module'?'Модуль':({course:'Все уроки',dictionary:'Словарь',review:'Повторение',exams:'Экзамены',progress:'Мой прогресс',settings:'Настройки'}[section]||'Обзор')}</strong></div></div><div class="topbar-right"><span class="header-streak">${icon('flame',16)} ${streak()} дн.</span>${actionButton('toggle-script',state.script==='latin'?'Аа → Ћ':'Ћ → Aa','chip', 'aria-label="Сменить письменность"')}${link('lesson/'+n.id,`${icon('play',15)} Продолжить`,'btn top-continue')}</div></header><main class="main-content" id="main-content">${content}</main><footer class="footer">SrpskiLab · Учебная платформа без обязательной регистрации. Данные хранятся в этом браузере. <a href="#/settings">Сохранить резервную копию</a></footer></div></div><div id="toast-region" role="status" aria-live="polite"></div><input id="import-file" type="file" accept="application/json,.json" hidden>`;}
function render(resetScroll=false){const r=route(),[rawKind,arg]=r.split('/'),kind=rawKind.split('?')[0];if(resetScroll)window.scrollTo(0,0);let content;switch(kind){case 'home':content=home();break;case 'course':content=course();break;case 'module':content=moduleView(+arg);break;case 'lesson':content=lessonView(byLesson[arg]);break;case 'dictionary':content=dictionaryView();break;case 'review':content=reviewView();break;case 'exams':content=examsView();break;case 'exam':content=examView(arg);break;case 'progress':content=progressView();break;case 'settings':content=settingsView();break;default:content=home();}$('#app').innerHTML=shell(content);if(ui.toast)showToast(ui.toast);}
function home(){const n=nextLesson(),done=totalDone(),due=dueWords().length,initial=!done;const hour=new Date().getHours(),greeting=hour<11?'Dobro jutro':hour<18?'Dobar dan':'Dobro veče';const todayDone=state.events[today()]?.lessons||0;
return `<section class="welcome"><div class="welcome-copy"><div class="eyebrow inverse">ТВОЁ ПРОСТРАНСТВО ДЛЯ ЯЗЫКА <span class="eyebrow-line"></span></div><h1>${greeting}, ${esc(state.name)}! <span class="wave">👋</span></h1><p>От первых <i>zdravo</i> до свободных разговоров в Нови-Саде. Маленький шаг каждый день — и сербский становится своим.</p><div class="hero-actions">${link('lesson/'+n.id,`${icon('play',18)} ${initial?'Начать первый урок':'Продолжить обучение'}`,'btn btn-light')}${link('course',`Посмотреть программу ${icon('arrow',17)}`,'btn btn-outline-light')}</div></div><div class="hero-art" aria-hidden="true"><span class="art-orbit orbit1"></span><span class="art-orbit orbit2"></span><div class="art-main">Љ</div><div class="art-bubble bubble1">Zdravo!</div><div class="art-bubble bubble2">Хвала ♡</div><span class="art-dots">···</span></div></section>
<div class="stats-grid"><div class="stat-card"><div class="stat-icon green">${icon('book',21)}</div><div class="stat-num">${done}<span> / 265</span></div><p>Пройдено уроков</p>${bar(done,265)}</div><div class="stat-card"><div class="stat-icon amber">${icon('flame',21)}</div><div class="stat-num">${streak()} <span>дней</span></div><p>Серия занятий</p><div class="small-muted">Каждый день имеет значение</div></div><div class="stat-card"><div class="stat-icon blue">${icon('cards',21)}</div><div class="stat-num">${seenCount()}</div><p>Слов встречено</p><div class="small-muted">Подтверждено практикой: ${numberKnown()}</div></div><div class="stat-card"><div class="stat-icon purple">${icon('target',21)}</div><div class="stat-num">${todayDone}<span> / ${state.goal}</span></div><p>Уроков сегодня</p>${bar(todayDone,state.goal)}</div></div>
<div class="home-grid"><section class="panel next-panel"><div class="panel-top"><div><div class="eyebrow">ТВОЙ СЛЕДУЮЩИЙ ШАГ</div><h2>${initial?'Всё начинается сегодня':'Продолжай с этого места'}</h2></div><span class="little-badge">${n.level} · урок ${n.num}</span></div><div class="next-title">${esc(n.title)}</div><p class="text-muted">${esc(n.note)}</p><div class="next-meta"><span>${icon('clock',16)} 30–40 мин</span><span>${icon('book',16)} ${esc(n.module.name)}</span></div>${link('lesson/'+n.id,`Открыть урок ${icon('arrow',18)}`,'btn primary wide')}</section><section class="panel review-panel"><div class="panel-top"><div><div class="eyebrow">ИНТЕРВАЛЬНОЕ ПОВТОРЕНИЕ</div><h2>Слова в памяти</h2></div><div class="review-symbol">${icon('bolt',25)}</div></div><div class="review-count">${due}<span> ${plural(due,['слово ждёт','слова ждут','слов ждут'])} повторения</span></div><p class="text-muted">Карточки возвращаются через 1, 3, 7, 14 и 30 дней. Повторяй то, что действительно изучал.</p>${link('review',due?'Начать повторение →':'Открыть карточки →','btn tertiary wide')}</section></div>
<section class="section-block"><div class="section-heading"><div><div class="eyebrow">ТВОЯ ДОРОЖНАЯ КАРТА</div><h2>Пять уровней, одна большая цель</h2></div>${link('course',`Вся программа ${icon('arrow',17)}`,'simple-link')}</div><div class="level-grid">${Object.entries(LEVELS).map(([code,x])=>{let d=levelDone(code),t=levelTotal(code);return `<a href="#/course?level=${code}" data-level-link="${code}" class="level-card"><span class="level-code" style="--level:${x.tone}">${code}</span><div><h3>${esc(x.title)}</h3><p>${esc(x.subtitle)}</p></div><div class="level-meta"><span>${d} / ${t} уроков</span><strong>${percent(d,t)}%</strong></div>${bar(d,t)}</a>`;}).join('')}</div></section>
<section class="practice-banner"><div class="practice-banner-icon">${icon('chat',28)}</div><div><h3>Язык начинается за пределами учебника</h3><p>Попробуй сегодня поздороваться, уточнить цену или задать короткий вопрос по-сербски.</p></div>${link('module/15','Практика для жизни →','btn btn-soft')}</section>`;}
function plural(n,forms){const x=Math.abs(n)%100,y=x%10;return forms[x>10&&x<20?2:y===1?0:y>=2&&y<=4?1:2];}
function course(){let filtered=modules.filter(m=>ui.level==='all'||m.level===ui.level).filter(m=>!ui.search||`${m.name} ${m.desc} ${m.id===1?'алфавит alphabet латиница кириллица':''} ${m.lessons.map(l=>l.title).join(' ')}`.toLowerCase().includes(ui.search.toLowerCase()));return `<section class="page-head"><div><div class="eyebrow">ПРОГРАММА A0 → B2</div><h1>Все 265 уроков</h1><p>31 тематический модуль: от кириллицы и первых приветствий до переписки, работы и естественной речи.</p></div><div class="head-decoration">Аа <span>Њ</span></div></section><div class="toolbar"><div class="filter-scroll">${['all',...Object.keys(LEVELS)].map(x=>`<button class="filter-tab ${ui.level===x?'selected':''}" data-action="set-level" data-level="${x}">${x==='all'?'Все уровни':x}</button>`).join('')}</div><label class="search-field">${icon('search',18)}<input id="course-search" value="${esc(ui.search)}" placeholder="Найти тему или урок…" autocomplete="off" aria-label="Поиск по урокам"></label></div><div class="course-list">${filtered.map(m=>moduleCard(m)).join('')||'<div class="empty">Ничего не найдено. Попробуй другой запрос.</div>'}</div>`;}
function moduleCard(m){const done=modDone(m),total=m.lessons.length;return `<article class="module-card"><div class="module-head"><div class="module-no">${String(m.id).padStart(2,'0')}</div><div class="module-info"><div class="eyebrow">${m.level} · МОДУЛЬ ${m.id}</div><h3>${esc(m.name)}</h3><p>${esc(m.desc)}</p></div><div class="module-progress"><strong>${done}/${total}</strong><span>уроков</span>${bar(done,total)}</div></div><div class="module-lessons">${m.lessons.map((l,i)=>{const id=`m${m.id}l${i+1}`,done=!!state.lessons[id]?.done;return `<a class="mini-lesson" href="#/lesson/${id}"><span class="lesson-number ${done?'complete':''}">${done?icon('check',14):String(i+1).padStart(2,'0')}</span><span>${esc(l.title)}</span>${icon('arrow',16)}</a>`;}).join('')}</div><div class="module-foot">${link('module/'+m.id,`Описание модуля ${icon('arrow',15)}`,'simple-link')}${link('lesson/'+`m${m.id}l${Math.min(done+1,total)}`,`${done?'Повторить':'Продолжить'} модуль ${icon('arrow',15)}`,'btn btn-small primary')}</div></article>`;}
function moduleView(id){const m=modules.find(x=>x.id===id);if(!m)return notFound();const done=modDone(m);return `<div class="back-row">${link('course',`${icon('back',16)} Все модули`,'simple-link')}</div><section class="module-hero"><div class="eyebrow">УРОВЕНЬ ${m.level} · МОДУЛЬ ${m.id}</div><h1>${esc(m.name)}</h1><p>${esc(m.desc)} На каждом занятии: теория, 8–11 слов, примеры, диалог, упражнения и проверка.</p><div class="module-hero-meter">${bar(done,m.lessons.length)}<span>${done} из ${m.lessons.length} уроков</span></div></section><div class="section-heading"><h2>Содержание модуля</h2><span class="small-muted">${m.lessons.length} уроков</span></div><div class="lesson-list">${m.lessons.map((l,i)=>{const s=state.lessons[`m${m.id}l${i+1}`];return `<a href="#/lesson/m${m.id}l${i+1}" class="lesson-list-row"><span class="lesson-list-index ${s?.done?'complete':''}">${s?.done?icon('check',18):String(i+1).padStart(2,'0')}</span><div><h3>${esc(l.title)}</h3><p>${esc(l.note)}</p></div><span class="lesson-list-status">${s?.done?`Пройдено · ${s.best}%`:'30–40 мин'}</span>${icon('arrow',18)}</a>`;}).join('')}</div><div class="module-callout">${icon('info',22)} <p>Все уроки доступны для просмотра. Результат уровня отмечается только после прохождения уроков и его теста. Автоматический тест не заменяет проверку речи преподавателем.</p></div>`;}
function notFound(){return `<section class="empty"><h2>Страница не найдена</h2>${link('home','Вернуться на главную','btn primary')}</section>`;}
function stageName(s){return {theory:'Теория',words:'Слова',dialogue:'Диалог',quiz:'Проверка',finish:'Результат'}[s];}
function currentStage(l){return ui.quiz?.lessonId===l.id?ui.quiz.stage:'theory';}
function lessonView(l){if(!l)return notFound();const stage=currentStage(l),ix=['theory','words','dialogue','quiz','finish'].indexOf(stage);return `<div class="back-row">${link('module/'+l.module.id,`${icon('back',16)} ${esc(l.module.name)}`,'simple-link')}<span>Урок ${l.num} из 265</span></div><div class="lesson-layout"><div class="lesson-main"><section class="lesson-heading"><div class="eyebrow">${l.level} · МОДУЛЬ ${l.module.id} · УРОК ${l.chapter}</div><h1>${esc(l.title)}</h1><p>${esc(l.note)}</p><div class="lesson-stepper">${['theory','words','dialogue','quiz','finish'].map((s,i)=>`<button class="lesson-step ${i===ix?'active':''} ${i<ix?'passed':''}" data-action="jump-step" data-step="${s}" ${i===4&&ix!==4?'disabled':''}><span>${i<ix?icon('check',14):i+1}</span>${stageName(s)}</button>`).join('')}</div></section><div class="lesson-body">${stage==='theory'?theoryStep(l):stage==='words'?wordsStep(l):stage==='dialogue'?dialogueStep(l):stage==='quiz'?quizStep(l):finishStep(l)}</div></div><aside class="lesson-aside"><div class="aside-box"><div class="eyebrow">ТЕКУЩИЙ УРОК</div><div class="aside-percent">${ix===4?'100':Math.round(ix/4*100)}<span>% пути</span></div>${bar(ix,4)}<div class="aside-info">${icon('clock',17)} 30–40 минут</div><div class="aside-info">${icon('cards',17)} ${wordsFor(l).length} слов в занятии</div><div class="aside-info">${icon('target',17)} 7 заданий в проверке</div></div><div class="aside-tip"><div class="tip-icon">${icon('spark',20)}</div><strong>Совет</strong><p>Не гонись за скоростью. Лучше 15 минут осмысленной практики, чем механическое пролистывание.</p></div></aside></div>`;}
function ensureLessonQuiz(l,stage='theory'){if(!ui.quiz||ui.quiz.lessonId!==l.id){ui.quiz={kind:'lesson',lessonId:l.id,stage,index:0,answers:[],checked:false,typed:'',chosen:'',roleAnswer:'',roleModel:false};}return ui.quiz;}
function theoryStep(l){ensureLessonQuiz(l);const m=l.module,i=l.chapter-1,exs=Array.from({length:4},(_,j)=>m.examples[(i*2+j)%m.examples.length]);return `<div class="step-eyebrow">01 / ИЗУЧАЕМ ТЕМУ</div><h2>Разберём главное</h2><div class="theory-intro"><span class="theory-icon">${icon('book',24)}</span><p>${esc(l.note)}</p></div><div class="theory-callout"><strong>Как это работает</strong><p>${esc(m.desc)} Прочитай примеры ниже, обрати внимание на формы слов и попробуй произнести каждую реплику самостоятельно. Если встречается незнакомая форма, ищи её в словаре модуля.</p></div>${window.SrpskiAddons?.render(l,sr,esc)||''}<h3 class="subheading">Живые примеры</h3><div class="example-list">${exs.map((e,i)=>`<div class="example-row"><span class="example-index">${String(i+1).padStart(2,'0')}</span><div><div class="serbian-text">${esc(sr(e.sr))}</div><div class="example-translation">${esc(e.ru)}</div></div><button class="speak-btn" data-speak="${enc(e.sr)}" aria-label="Произнести пример">${icon('volume',19)}</button></div>`).join('')}</div><div class="lesson-hint">${icon('info',19)} Сербское произношение из браузера доступно, только если на устройстве установлен голос для сербского (sr-RS). Кириллический переключатель находится вверху.</div><div class="step-actions">${actionButton('step-words',`Перейти к словам ${icon('arrow',19)}`,'primary')}</div>`;}
function wordsStep(l){ensureLessonQuiz(l,'words');lessonMarkSeen(l);return `<div class="step-eyebrow">02 / АКТИВНЫЙ СЛОВАРЬ</div><h2>Слова этого урока</h2><p class="section-intro">Прочитай, повтори и постарайся вспомнить перевод до того, как посмотришь на него. Эти слова появятся в карточках повторения.</p><div class="vocab-table"><div class="vocab-header"><span>СЕРБСКИЙ</span><span>ПЕРЕВОД И КОНТЕКСТ</span><span></span></div>${wordsFor(l).map((w,i)=>`<div class="vocab-row"><div><span class="vocab-ordinal">${String(i+1).padStart(2,'0')}</span><strong>${esc(sr(w.sr))}</strong><small>${esc(state.script==='latin'?romanToCyr(w.sr):w.sr)}</small></div><div><span>${esc(w.ru)}</span>${w.usage?`<small>${esc(sr(w.usage))} — ${esc(w.usageRu)}</small>`:''}</div><button class="speak-btn" data-speak="${enc(w.sr)}" aria-label="Произнести ${esc(w.sr)}">${icon('volume',18)}</button></div>`).join('')}</div><div class="lesson-hint">${icon('cards',18)} Слова не считаются выученными только от просмотра. Для этого есть карточки с интервальным повторением.</div><div class="step-actions">${actionButton('step-theory',`${icon('back',17)} Назад`,'secondary')}${actionButton('step-dialogue',`К диалогу ${icon('arrow',19)}`,'primary')}</div>`;}
function dialogueStep(l){ensureLessonQuiz(l,'dialogue');const rows=l.module.dialogue,reply=rows.find(x=>x.by==='Ты')||rows[1];return `<div class="step-eyebrow">03 / ЖИВАЯ РЕЧЬ</div><h2>Попрактикуемся в разговоре</h2><p class="section-intro">Прочитай диалог вслух. Сначала попробуй понять реплики без русского перевода.</p><div class="dialogue-controls">${actionButton('translations',ui.dialogTranslations?'Скрыть перевод':'Показать перевод','chip')}</div><div class="chat-scene">${rows.map(x=>`<div class="chat-row ${x.by==='Ты'?'chat-own':''}"><span class="chat-avatar">${x.by==='Ты'?'Я':esc(x.by[0])}</span><div><span class="chat-author">${esc(x.by)}</span><div class="chat-balloon">${esc(sr(x.sr))}${ui.dialogTranslations?`<small>${esc(x.ru)}</small>`:''}</div>${`<button class="chat-audio" data-speak="${enc(x.sr)}">${icon('volume',15)} Произнести</button>`}</div></div>`).join('')}</div><div class="roleplay"><div class="eyebrow">ТЕПЕРЬ ТВОЯ ОЧЕРЕДЬ</div><h3>Ответь самостоятельно</h3><p>Представь себя в этой ситуации. Напиши на сербском подходящую реплику. Уместных ответов может быть несколько: это тренировка, а не автоматическая оценка речи.</p><label class="field-label" for="role-input">Твой ответ</label><textarea id="role-input" class="text-input role-input" placeholder="Например: Dobar dan...">${esc(ui.quiz?.roleAnswer||'')}</textarea><div class="role-buttons">${actionButton('show-model',ui.quiz?.roleModel?'Скрыть образец':'Посмотреть пример ответа','secondary')}</div>${ui.quiz?.roleModel?`<div class="model-answer"><strong>Один из возможных ответов:</strong><p>${esc(sr(reply.sr))}</p><small>${esc(reply.ru)}</small></div>`:''}</div><div class="step-actions">${actionButton('step-words',`${icon('back',17)} Назад`,'secondary')}${actionButton('step-quiz',`К заданиям ${icon('arrow',19)}`,'primary')}</div>`;}
function choices(correct,from,seed){const candidates=[...new Set(from.filter(x=>x!==correct&&x))];const others=stableShuffle(candidates,seed).slice(0,3);return stableShuffle([correct,...others],seed+77);}
function buildLessonQuestions(l){const m=l.module,w=wordsFor(l),i=l.chapter-1,e=m.examples[(i*3+1)%m.examples.length],e2=m.examples[(i*3+3)%m.examples.length],d=m.dialogue[(i+1)%m.dialogue.length];const v=w[(i*2+1)%w.length],v2=w[(i*2+3)%w.length],v3=w[(i*2+5)%w.length];const token=e2.sr.match(/[\p{L}]{4,}/u)?.[0]||e2.sr.split(' ')[0];const where=e2.sr.replace(token,'_____');const tokOptions=m.examples.flatMap(x=>x.sr.match(/[\p{L}]{4,}/gu)||[]).filter(x=>x.toLowerCase()!==token.toLowerCase());const scriptAnswer=l.level==='A0'||l.level==='A1'?romanToCyr(v3.sr):v3.sr;
return [
{type:'choice',prompt:'Что означает слово или выражение?',display:sr(v.sr),answer:v.ru,options:choices(v.ru,m.vocab.map(x=>x.ru),l.num*51),explain:`«${v.sr}» — ${v.ru}.`},
{type:'choice',prompt:'Как сказать по-сербски?',display:v2.ru,answer:v2.sr,options:choices(v2.sr,m.vocab.map(x=>x.sr),l.num*53),isSerbian:true,explain:`${v2.sr} — ${v2.ru}.`},
{type:'type',prompt:l.level==='A0'||l.level==='A1'?'Перепиши сербской кириллицей':'Напиши сербское слово или выражение',display:l.level==='A0'||l.level==='A1'?v3.sr:v3.ru,answer:scriptAnswer,explain:l.level==='A0'||l.level==='A1'?`Латиница: ${v3.sr}. Кириллица: ${romanToCyr(v3.sr)}.`:`${v3.sr} — ${v3.ru}.`},
{type:'choice',prompt:'Прочитай фразу. Что она значит?',display:sr(e.sr),answer:e.ru,options:choices(e.ru,m.examples.map(x=>x.ru),l.num*57),explain:`${e.sr} — ${e.ru}.`},
{type:'type',prompt:'Вспомни сербский перевод',display:v.sr===v2.sr?v3.ru:v.ru,answer:v.sr===v2.sr?v3.sr:v.sr,explain:`${v.sr} — ${v.ru}.`},
{type:'choice',prompt:'Какое слово пропущено?',display:sr(where),answer:token,options:choices(token,tokOptions,l.num*59),isSerbian:true,explain:`Полная фраза: ${e2.sr} — ${e2.ru}.`},
{type:'choice',prompt:'Что сказал собеседник?',display:sr(d.sr),answer:d.ru,options:choices(d.ru,[...m.dialogue.map(x=>x.ru),...m.examples.map(x=>x.ru)],l.num*61),explain:`${d.sr} — ${d.ru}.`}
];}
function buildExamQuestions(level){const all=lessons.filter(l=>l.level===level),sel=[];for(let i=0;i<20;i++){const l=all[(i*7+Math.floor(i/5)*11)%all.length];const x=buildLessonQuestions(l);sel.push({...x[(i*3+Math.floor(i/3))%x.length],topic:l.title});}return sel;}
function quizStep(l){const q=ensureLessonQuiz(l,'quiz');if(q.kind!=='lesson'){ui.quiz=null;return quizStep(l);}q.questions??=buildLessonQuestions(l);return renderQuestion(q,`УРОК ${l.num} · ПРОВЕРКА`,()=>`<div class="step-actions only-back">${actionButton('step-dialogue',`${icon('back',17)} Вернуться к диалогу`,'secondary')}</div>`);}
function renderQuestion(q,brow,backHtml){const question=q.questions[q.index];if(!question)return '<p>Тест пока не загружен.</p>';const isDone=q.checked;const ans=q.answers[q.index];return `<div class="step-eyebrow">${brow}</div><div class="quiz-top"><div><h2>Вопрос ${q.index+1} из ${q.questions.length}</h2><p class="text-muted">${q.kind==='exam'?'Итоговый тренировочный тест':'Проверь, что осталось в памяти'}</p></div><span class="quiz-score">${q.answers.filter(a=>a.correct).length} верно</span></div>${bar(q.index,q.questions.length,'quiz-progress')}<div class="quiz-task"><div class="quiz-instruction">${esc(question.prompt)}</div><div class="quiz-display ${question.display.length>85?'long':''}">${esc(question.display)}</div>${question.type==='choice'?`<div class="quiz-options">${question.options.map((x,i)=>{const chosen=q.chosen===x,cls=isDone?(x===question.answer?'correct':chosen?'wrong':''):chosen?'chosen':'';return `<button class="quiz-option ${cls}" data-action="choose-answer" data-choice="${enc(x)}" ${isDone?'disabled':''}><span class="answer-key">${String.fromCharCode(65+i)}</span><span>${esc(question.isSerbian?sr(x):x)}</span>${isDone&&x===question.answer?icon('check',19):''}</button>`;}).join('')}</div>`:`<form id="quiz-form" class="quiz-form"><label class="field-label" for="quiz-typed">Твой ответ</label><input id="quiz-typed" class="text-input ${isDone&&!ans.correct?'input-error':''}" autocomplete="off" value="${esc(q.typed||'')}" placeholder="Введи ответ самостоятельно..." ${isDone?'disabled':''} required>${!isDone?`<button class="btn primary" type="submit">Проверить ответ ${icon('arrow',18)}</button>`:''}</form>`}${isDone?`<div class="quiz-feedback ${ans.correct?'positive':'negative'}"><div><strong>${ans.correct?'Верно!':'Пока неверно'}</strong><p>${esc(question.explain)}</p>${!ans.correct?`<small>Ожидаемый ответ: <b>${esc(question.answer)}</b></small>`:''}</div></div><button class="btn primary next-q" data-action="quiz-next">${q.index+1===q.questions.length?'Завершить проверку':'Следующий вопрос'} ${icon('arrow',18)}</button>`:''}</div>${backHtml?backHtml():''}`;}
function finalizeQuiz(q){const ok=q.answers.filter(x=>x.correct).length,pct=percent(ok,q.questions.length);if(q.kind==='lesson'){const old=state.lessons[q.lessonId]||{},l=byLesson[q.lessonId];state.lessons[q.lessonId]={best:Math.max(old.best||0,pct),attempts:(old.attempts||0)+1,done:old.done||pct>=70,last:today()};if(pct>=70&&!old.done)track('lessons');else track('tests');q.stage='finish';save();}else{const old=state.exams[q.level]||{};state.exams[q.level]={best:Math.max(old.best||0,pct),attempts:(old.attempts||0)+1,last:today(),passed:old.passed||pct>=80};track('tests');q.stage='finish';save();}}
function finishStep(l){const q=ensureLessonQuiz(l,'finish'),r=state.lessons[l.id];if(!r)return theoryStep(l);const next=lessons[l.num]||null,complete=!!r.done;return `<div class="completion-card"><div class="completion-icon">${icon(complete?'check':'target',38)}</div><div class="eyebrow">РЕЗУЛЬТАТ УРОКА ${l.num}</div><h2>${complete?'Урок пройден!':'У тебя уже есть основа'}</h2><p>${complete?'Ты прошёл проверку. Закрепим изученные слова интервальным повторением.':'Для зачёта нужно минимум 5 из 7 правильных ответов. Повтори примеры и попробуй ещё раз.'}</p><div class="big-score">${r.best}<span>%</span></div><span class="score-caption">Лучший результат теста · ${r.attempts} ${plural(r.attempts,['попытка','попытки','попыток'])}</span><div class="completion-actions">${complete&&next?link('lesson/'+next.id,`Следующий урок ${icon('arrow',18)}`,'btn primary'):''}${actionButton('restart-lesson-quiz',`Пройти проверку ещё раз ${icon('target',17)}`,'secondary')}${link('review','Повторить карточки','btn tertiary')}</div></div><div class="homework"><div class="eyebrow">ПРАКТИКА В РЕАЛЬНОЙ ЖИЗНИ</div><h3>Задание вне сайта</h3><p>${esc(l.level==='A0'?'Попробуй использовать одну новую фразу в магазине, подъезде или на улице в Нови-Саде.':l.level==='A1'?'Составь три коротких предложения по теме урока и скажи одно из них вслух.':l.level==='A2'?'Напиши короткое реальное сообщение по теме урока и проверь, понятно ли его содержание.':l.level==='B1'?'Объясни собственными словами ситуацию из урока и уточни мнение собеседника.':'Составь связный аргумент, письмо или устный пересказ по теме урока.')} </p></div>`;}
function dictionaryView(){const q=ui.dictSearch.toLowerCase().trim();let items=dictionary.filter(w=>(ui.dictLevel==='all'||w.level===ui.dictLevel)&&(ui.dictMode==='all'||(ui.dictMode==='seen'&&state.seen[w.key])||(ui.dictMode==='known'&&state.reviews[w.key]?.stage>=3))&&(!q||`${w.sr} ${romanToCyr(w.sr)} ${w.ru} ${w.module.name}`.toLowerCase().includes(q)));return `<section class="page-head"><div><div class="eyebrow">ТВОЙ ЛИЧНЫЙ СЛОВАРЬ</div><h1>Слова, которые работают</h1><p>${dictionary.length} уникальных выражений в материалах курса. Добавляй их в интервальное повторение по мере прохождения уроков.</p></div><div class="head-icon">${icon('cards',43)}</div></section><div class="toolbar dict-toolbar"><div class="filter-scroll">${[['all','Все'],['seen','Встреченные'],['known','Закреплённые']].map(([v,t])=>`<button class="filter-tab ${ui.dictMode===v?'selected':''}" data-action="dict-mode" data-value="${v}">${t}</button>`).join('')}</div><label class="search-field">${icon('search',18)}<input id="dict-search" value="${esc(ui.dictSearch)}" placeholder="Слово или перевод…" autocomplete="off" aria-label="Поиск слов"></label><select class="select" id="dict-level" aria-label="Фильтр по уровню">${['all',...Object.keys(LEVELS)].map(x=>`<option value="${x}" ${ui.dictLevel===x?'selected':''}>${x==='all'?'Все уровни':x}</option>`).join('')}</select></div><div class="dictionary-meta">Найдено: <b>${items.length}</b> · Встречено: <b>${seenCount()}</b> · Закреплено: <b>${numberKnown()}</b></div><div class="dict-grid">${items.slice(0,ui.showMoreWords?items.length:60).map(w=>`<article class="dict-card"><div class="dict-card-header"><span class="tag-level">${w.level}</span>${state.reviews[w.key]?.stage>=3?`<span class="tag-known">${icon('check',13)} Закреплено</span>`:state.seen[w.key]?'<span class="tag-seen">В повторении</span>':'<span class="tag-new">Новое</span>'}</div><div class="dict-word">${esc(sr(w.sr))}</div><div class="dict-subword">${esc(state.script==='latin'?romanToCyr(w.sr):w.sr)}</div><p>${esc(w.ru)}</p>${w.usage?`<div class="dict-context">${esc(sr(w.usage))}<small>${esc(w.usageRu)}</small></div>`:''}<div class="dict-card-bottom"><span>${esc(w.module.name)}</span><button data-speak="${enc(w.sr)}" class="speak-btn" aria-label="Произнести слово">${icon('volume',17)}</button><button data-action="add-word" data-word="${enc(w.key)}" class="mini-action" aria-label="Добавить слово в карточки" title="Добавить слово в повторение">${icon('cards',16)}</button></div></article>`).join('')||'<div class="empty">По этому запросу слов пока нет.</div>'}</div>${!ui.showMoreWords&&items.length>60?actionButton('show-more',`Показать остальные ${items.length-60} слов ${icon('chev',17)}`,'secondary show-more'):''}`;}
function reviewView(){const due=dueWords();const seen=dictionary.filter(w=>state.seen[w.key]);if(!seen.length)return `<section class="page-head"><div><div class="eyebrow">ИНТЕРВАЛЬНОЕ ПОВТОРЕНИЕ</div><h1>Карточки памяти</h1><p>Чтобы слова появились здесь, открой второй шаг любого урока — «Слова».</p></div></section><div class="empty-illustrated">${icon('cards',54)}<h2>Пока нечего повторять</h2>${link('lesson/'+nextLesson().id,'Открыть первый урок','btn primary')}</div>`;if(!due.length)return `<section class="page-head"><div><div class="eyebrow">ИНТЕРВАЛЬНОЕ ПОВТОРЕНИЕ</div><h1>Всё повторено!</h1><p>На сегодня нет карточек, у которых наступила дата повторения.</p></div></section><div class="empty-illustrated">${icon('check',54)}<h2>Ты справился со всеми карточками</h2><p>Следующие появятся в назначенный день.</p>${link('course','Продолжить уроки','btn primary')}</div>`;const w=due[0],r=state.reviews[w.key],show=ui.flashFlip;return `<section class="page-head"><div><div class="eyebrow">УЧИМ НЕ КОЛИЧЕСТВО, А ПАМЯТЬ</div><h1>Повторение слов</h1><p>Вспомни значение до переворота. После этого честно оцени, удалось ли вспомнить.</p></div><div class="review-head-badge">${due.length}<small>сегодня</small></div></section><div class="flash-layout"><div class="flash-main"><div class="flash-meta"><span>${icon('cards',17)} Осталось ${due.length}</span><span>Этап памяти: ${r?.stage||0}/5</span></div><button class="flashcard ${show?'flipped':''}" data-action="flip-card" aria-label="Перевернуть карточку"><span class="flash-eyebrow">${show?'ПЕРЕВОД':'СЕРБСКИЙ ЯЗЫК'}</span><span class="flash-word">${esc(show?w.ru:sr(w.sr))}</span>${show?`<span class="flash-script">${esc(sr(w.sr))}</span>${w.usage?`<span class="flash-example">${esc(sr(w.usage))}<br>${esc(w.usageRu)}</span>`:''}`:`<span class="flash-script">${esc(state.script==='latin'?romanToCyr(w.sr):w.sr)}</span>`}<span class="flash-instruction">${icon('cards',17)} Нажми, чтобы перевернуть</span></button><div class="flash-actions">${show?`<button class="btn again" data-action="rate-word" data-rating="again">${icon('back',18)} Не вспомнил</button><button class="btn good" data-action="rate-word" data-rating="good">Вспомнил ${icon('check',19)}</button>`:actionButton('flip-card',`Показать перевод ${icon('arrow',19)}`,'primary wide')}</div></div><aside class="flash-sidebar"><div class="panel"><div class="eyebrow">КАК ЭТО РАБОТАЕТ</div><h3>Повторяй вовремя</h3><p>При правильном воспоминании следующий показ откладывается. Если забыл — возвращаем слово в начало.</p><div class="intervals">${[1,3,7,14,30].map((n,i)=>`<div class="interval ${r?.stage===i+1?'on':''}">${n} ${plural(n,['день','дня','дней'])}</div>`).join('')}</div></div></aside></div>`;}
function examsView(){return `<section class="page-head"><div><div class="eyebrow">ПРОВЕРКА УРОВНЕЙ</div><h1>Экзамены и зачёты</h1><p>В каждом уровне — 20 автоматически проверяемых заданий. Проходной порог — 80%. Для отметки освоения всех материалов уровня нужно также пройти его уроки.</p></div><div class="head-icon">${icon('award',43)}</div></section><div class="exams-list">${Object.entries(LEVELS).map(([code,x])=>{const e=state.exams[code],d=levelDone(code),t=levelTotal(code),pass=e?.passed&&d===t;return `<article class="exam-card"><div class="exam-code" style="--level:${x.tone}">${code}</div><div class="exam-info"><h2>Экзамен ${code} <span>· ${esc(x.title)}</span></h2><p>${esc(x.subtitle)}. Пройдено ${d}/${t} уроков.</p>${bar(d,t)}<div class="exam-tags"><span>${icon('target',14)} 20 вопросов</span><span>${icon('clock',14)} ~15 минут</span><span>${e?`Лучший результат: ${e.best}%`:'Не сдавался'}</span></div></div><div class="exam-cta"><span class="status-pill ${pass?'success':e?.passed?'soft':'muted'}">${pass?'Уровень пройден':e?.passed?'Тест сдан · уроки не завершены':'Впереди'}</span>${link('exam/'+code,`${e?'Повторить':'Начать'} экзамен ${icon('arrow',17)}`,'btn primary')}</div></article>`;}).join('')}</div><div class="module-callout">${icon('info',20)} <p>Тесты проверяют лексику, чтение и отдельные письменные формы. Они не определяют официальный уровень CEFR и не могут объективно оценить произношение и живой разговор.</p></div>`;}
function examView(level){if(!LEVELS[level])return notFound();if(!ui.quiz||ui.quiz.kind!=='exam'||ui.quiz.level!==level){ui.quiz={kind:'exam',level,stage:'intro',index:0,answers:[],checked:false,typed:'',chosen:'',questions:buildExamQuestions(level)};}const q=ui.quiz;if(q.stage==='finish'){const ex=state.exams[level],passing=ex.best>=80,all=levelDone(level)===levelTotal(level);return `<div class="back-row">${link('exams',`${icon('back',16)} К экзаменам`,'simple-link')}</div><div class="completion-card exam-finish"><div class="completion-icon">${icon(passing?'award':'target',38)}</div><div class="eyebrow">ИТОГОВЫЙ ТЕСТ ${level}</div><h1>${passing?'Тренировочный тест сдан':'Есть что закрепить'}</h1><div class="big-score">${ex.best}<span>%</span></div><p>${passing?(all?'Ты завершил уроки уровня и набрал нужный балл в автоматическом тесте.':'Нужный балл набран! Но для отметки уровня пройди все его уроки.'):'Проходной порог — 80%. Повтори материалы и попробуй ещё раз.'}</p><div class="completion-actions">${actionButton('restart-exam',`Повторить тест ${icon('target',17)}`,'secondary')}${link('course?level='+level,'Вернуться к урокам','btn primary')}</div></div><div class="homework"><div class="eyebrow">ДОПОЛНИТЕЛЬНАЯ САМОПРОВЕРКА</div><h3>Письмо и разговор</h3><p>${esc({A0:'Напиши 4 приветствия и представься.',A1:'Расскажи 5–7 предложений о семье и своём обычном дне.',A2:'Составь обращение в учреждение и разыграй телефонный разговор.',B1:'Напиши связный рассказ о проблеме и способе её решения (100–150 слов).',B2:'Подготовь аргументированное письмо или устное выступление (200–250 слов).'}[level])} Этот навык пока оценивай самостоятельно или с преподавателем.</p></div>`;}if(q.stage==='intro')return `<div class="back-row">${link('exams',`${icon('back',16)} Экзамены`,'simple-link')}</div><section class="exam-intro"><div class="eyebrow">ИТОГОВАЯ ПРОВЕРКА</div><div class="exam-intro-code">${level}</div><h1>${esc(LEVELS[level].title)}</h1><p>20 вопросов по лексике, буквам, коротким фразам и структурам уровня. В ходе проверки подсказки не показываются до ответа; после ошибки мы объясним ожидаемый вариант.</p><div class="exam-intro-facts"><span>${icon('target',18)} 20 заданий</span><span>${icon('clock',18)} Около 15 минут</span><span>${icon('check',18)} Порог 80%</span></div>${actionButton('start-exam',`Начать проверку ${icon('arrow',19)}`,'primary')}<p class="footnote">Это учебный тест платформы, а не государственный экзамен и не сертификат CEFR.</p></section>`;return `<div class="back-row">${link('exams',`${icon('back',16)} К экзаменам`,'simple-link')}</div><div class="exam-workspace">${renderQuestion(q,`ЭКЗАМЕН ${level}`)}</div>`;}
function progressView(){const d=totalDone(),dates=Array.from({length:14},(_,i)=>{const x=new Date();x.setDate(x.getDate()-13+i);return {day:today(x),date:x};});const max=Math.max(1,...dates.map(x=>state.events[x.day]?.lessons||0));return `<section class="page-head"><div><div class="eyebrow">ЛИЧНЫЙ УЧЕБНЫЙ ДНЕВНИК</div><h1>Твой прогресс</h1><p>Результаты основаны на выполненных упражнениях, а не на простом открытии страницы урока.</p></div><div class="head-icon">${icon('chart',44)}</div></section><div class="stats-grid"><div class="stat-card"><div class="stat-icon green">${icon('check',20)}</div><div class="stat-num">${d}</div><p>Уроков пройдено</p></div><div class="stat-card"><div class="stat-icon amber">${icon('flame',20)}</div><div class="stat-num">${streak()}</div><p>Дней подряд</p></div><div class="stat-card"><div class="stat-icon blue">${icon('cards',20)}</div><div class="stat-num">${numberKnown()}</div><p>Слов закреплено</p></div><div class="stat-card"><div class="stat-icon purple">${icon('award',20)}</div><div class="stat-num">${Object.values(state.exams).filter(x=>x.passed).length}</div><p>Учебных тестов уровня сдано</p></div></div><div class="progress-page-grid"><div class="panel"><div class="section-heading compact"><div><div class="eyebrow">АКТИВНОСТЬ</div><h2>Последние 14 дней</h2></div></div><div class="activity-chart">${dates.map(x=>{const n=state.events[x.day]?.lessons||0;return `<div class="activity-col" title="${esc(x.day)}: ${n} уроков"><span>${n||''}</span><div class="activity-bar" style="height:${Math.max(5,Math.round(n/max*140))}px"></div><small>${x.date.getDate()}</small></div>`;}).join('')}</div><div class="activity-note">${icon('info',15)} Высота столбца — число завершённых уроков за день.</div></div><div class="panel"><div class="section-heading compact"><div><div class="eyebrow">УРОВНИ</div><h2>Где ты сейчас</h2></div></div>${Object.entries(LEVELS).map(([k,v])=>`<div class="progress-level"><div><span class="tag-level">${k}</span><strong>${esc(v.title)}</strong><small>${levelDone(k)} / ${levelTotal(k)}</small></div>${bar(levelDone(k),levelTotal(k))}</div>`).join('')}</div></div><section class="panel errors-panel"><div class="section-heading compact"><div><div class="eyebrow">ПЕРСОНАЛЬНЫЙ РАЗБОР</div><h2>Последние ошибки</h2></div></div>${state.errors.length?`<div class="errors-list">${[...state.errors].reverse().slice(0,8).map(x=>`<div class="error-item"><strong>${esc(x.prompt)}</strong><p>${esc(x.display)} · Твой ответ: <b>${esc(x.typed||'—')}</b></p><small>Верный вариант: ${esc(x.expected)}</small></div>`).join('')}</div>`:'<p class="text-muted">Ошибок пока нет. Когда начнёшь проходить тесты, здесь появятся темы для повторения.</p>'}</section>`;}
function settingsView(){return `<section class="page-head"><div><div class="eyebrow">НАСТРОЙ САЙТ ПОД СЕБЯ</div><h1>Настройки</h1><p>Прогресс хранится локально в браузере. Для переноса на другое устройство скачай резервную копию и импортируй её там.</p></div><div class="head-icon">${icon('settings',44)}</div></section><div class="settings-grid"><section class="panel"><h2>Профиль и занятия</h2><div class="setting-block"><label class="field-label" for="profile-name">Как к тебе обращаться</label><input class="text-input" id="profile-name" maxlength="40" value="${esc(state.name)}"></div><div class="setting-block"><label class="field-label">Письменность</label><div class="segmented">${[['latin','Latinica · Zdravo'],['cyrillic','Ћирилица · Здраво']].map(([v,x])=>`<button data-action="set-script" data-value="${v}" class="${state.script===v?'active':''}">${x}</button>`).join('')}</div></div><div class="setting-block"><label class="field-label">Тема оформления</label><div class="segmented">${[['light',`${icon('sun',17)} Светлая`],['dark',`${icon('moon',17)} Тёмная`]].map(([v,x])=>`<button data-action="set-theme" data-value="${v}" class="${state.theme===v?'active':''}">${x}</button>`).join('')}</div></div><div class="setting-block"><label class="field-label" for="daily-goal">Цель на день</label><select id="daily-goal" class="select wide">${[1,2,3,4].map(n=>`<option value="${n}" ${state.goal===n?'selected':''}>${n} ${plural(n,['урок','урока','уроков'])} в день</option>`).join('')}</select></div>${actionButton('save-profile',`Сохранить настройки ${icon('check',18)}`,'primary')}</section><section class="panel"><h2>Резервная копия</h2><p class="text-muted">Сохраняет завершённые уроки, ошибки, интервальные карточки, экзамены и настройки. Формат — обычный JSON.</p><div class="stacked-buttons">${actionButton('export',`${icon('download',18)} Скачать мой прогресс`,'secondary wide')}${actionButton('import',`${icon('upload',18)} Импортировать прогресс`,'secondary wide')}</div><div class="settings-alert">${icon('info',20)} Если очистить данные браузера без резервной копии, учебный прогресс может быть потерян.</div><h3>Начать сначала</h3><p class="text-muted">Обнуляет прогресс и карточки только в этом браузере. Курс и уроки останутся.</p>${actionButton('reset',`${icon('close',16)} Сбросить прогресс`,'danger')}</section></div><div class="module-callout">${icon('volume',20)} <p>Кнопка озвучивания работает только при наличии в браузере/операционной системе синтезатора сербской речи. Если его нет, сайт не подменяет сербское произношение голосом другого языка.</p></div>`;}
function toast(msg){ui.toast=msg;showToast(msg);}
function showToast(msg){const holder=$('#toast-region');if(!holder)return;holder.innerHTML=`<div class="toast">${icon('info',18)} ${esc(msg)} <button data-action="dismiss-toast" aria-label="Закрыть">${icon('close',15)}</button></div>`;}
function goStage(stage){const l=byLesson[route().split('/')[1]];if(!l)return;const q=ensureLessonQuiz(l);q.stage=stage;if(stage==='words')lessonMarkSeen(l);if(stage==='quiz'){q.questions=buildLessonQuestions(l);q.index=0;q.answers=[];q.checked=false;q.chosen='';q.typed='';}render(true);}
function checkAnswer(answer){const q=ui.quiz,question=q.questions[q.index];if(q.checked)return;const correct=norm(answer)===norm(question.answer);q.answers[q.index]={correct,answer};q.checked=true;q.typed=question.type==='type'?answer:'';q.chosen=question.type==='choice'?answer:'';if(!correct)logError(question,answer);render();}
function rateWord(key,rating){const old=state.reviews[key]||{stage:0},stage=rating==='good'?Math.min(5,old.stage+1):0;const days=[1,3,7,14,30];const due=rating==='good'?Date.now()+days[stage-1]*86400000:Date.now()+60000;state.reviews[key]={stage,due,last:Date.now()};track('reviews');ui.flashFlip=false;render();}
function playAudio(str){if(!('speechSynthesis'in window)){toast('Озвучивание не поддерживается этим браузером.');return;}const voices=speechSynthesis.getVoices(),voice=voices.find(v=>/^sr([_-]|$)/i.test(v.lang));if(!voice){toast('Сербский голос (sr-RS) не установлен. Для точного произношения добавь сербский голос в настройках устройства.');return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(str);utterance.lang='sr-RS';utterance.voice=voice;utterance.rate=0.83;utterance.pitch=1;speechSynthesis.speak(utterance);}
function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`srpskilab-progress-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('Резервная копия скачана. Храни её в надёжном месте.');}
async function importData(file){if(!file||file.size>5e6){toast('Нужен файл JSON размером до 5 МБ.');return;}try{const d=JSON.parse(await file.text());if(!d||d.version!==1||typeof d.lessons!=='object'||typeof d.reviews!=='object'||typeof d.seen!=='object'||typeof d.events!=='object')throw Error('bad');if(!window.confirm('Заменить текущий прогресс данными из выбранного файла?'))return;Object.assign(state,blankState(),d);state.name=String(state.name||'Ученик').slice(0,40);state.theme=['light','dark'].includes(state.theme)?state.theme:'light';state.script=['latin','cyrillic'].includes(state.script)?state.script:'latin';state.goal=[1,2,3,4].includes(+state.goal)?+state.goal:1;state.errors=Array.isArray(state.errors)?state.errors.slice(-120):[];save();ui.quiz=null;render();toast('Прогресс восстановлен из резервной копии.');}catch{toast('Не удалось прочитать резервную копию. Проверь файл.');}}
function restartLessonQuiz(){const l=byLesson[route().split('/')[1]];if(l){ui.quiz={kind:'lesson',lessonId:l.id,stage:'quiz',index:0,answers:[],checked:false,typed:'',chosen:'',questions:buildLessonQuestions(l)};render(true);}}
const app=document;
app.addEventListener('click',event=>{
  const speak=event.target.closest('[data-speak]');if(speak){playAudio(decodeURIComponent(speak.dataset.speak));return;}
  const btn=event.target.closest('[data-action]');if(!btn)return;
  const action=btn.dataset.action;event.preventDefault();
  if(action==='dismiss-toast'){$('#toast-region').innerHTML='';ui.toast='';return;}
  if(action==='toggle-menu'){ui.navOpen=!ui.navOpen;render();return;}
  if(action==='toggle-script'||action==='set-script'){state.script=action==='toggle-script'?(state.script==='latin'?'cyrillic':'latin'):btn.dataset.value;save();render();return;}
  if(action==='set-theme'){state.theme=btn.dataset.value;save();render();return;}
  if(action==='set-level'){ui.level=btn.dataset.level;render();return;}
  if(action==='dict-mode'){ui.dictMode=btn.dataset.value;ui.showMoreWords=false;render();return;}
  if(action==='show-more'){ui.showMoreWords=true;render();return;}
  if(action==='add-word'){const key=decodeURIComponent(btn.dataset.word);if(dictMap.has(key)){state.seen[key]??={date:today(),lesson:'dictionary'};save();render();toast('Слово добавлено в карточки повторения.');}return;}
  if(action==='flip-card'){ui.flashFlip=!ui.flashFlip;render();return;}
  if(action==='rate-word'){const w=dueWords()[0];if(w)rateWord(w.key,btn.dataset.rating);return;}
  if(action==='translations'){ui.dialogTranslations=!ui.dialogTranslations;render();return;}
  if(action==='show-model'){ui.quiz.roleModel=!ui.quiz.roleModel;render();return;}
  if(action==='choose-answer'){if(!ui.quiz?.checked)checkAnswer(decodeURIComponent(btn.dataset.choice));return;}
  if(action==='quiz-next'){const q=ui.quiz;if(q&&q.checked){if(q.index+1>=q.questions.length){finalizeQuiz(q);}else{q.index++;q.checked=false;q.typed='';q.chosen='';}render(true);}return;}
  if(action==='jump-step'){if(btn.dataset.step!=='finish')goStage(btn.dataset.step);return;}
  if(action.startsWith('step-')){goStage(action.slice(5));return;}
  if(action==='restart-lesson-quiz'){restartLessonQuiz();return;}
  if(action==='start-exam'){ui.quiz.stage='quiz';render(true);return;}
  if(action==='restart-exam'){ui.quiz=null;location.hash='#/exam/'+route().split('/')[1];render(true);return;}
  if(action==='export'){exportData();return;}
  if(action==='import'){$('#import-file')?.click();return;}
  if(action==='save-profile'){state.name=($('#profile-name')?.value||'Ученик').trim().slice(0,40);state.goal=+($('#daily-goal')?.value||1);save();render();toast('Настройки сохранены.');return;}
  if(action==='reset'){if(window.confirm('Точно удалить ВЕСЬ учебный прогресс в этом браузере? Сначала рекомендуется скачать резервную копию.')){Object.assign(state,blankState());save();ui.quiz=null;location.hash='#/home';render(true);toast('Прогресс в этом браузере сброшен.');}return;}
});
app.addEventListener('submit',ev=>{if(ev.target.id==='quiz-form'){ev.preventDefault();const val=$('#quiz-typed')?.value?.trim();if(val)checkAnswer(val);}});
app.addEventListener('input',ev=>{if(ev.target.id==='course-search'||ev.target.id==='dict-search'){const isCourse=ev.target.id==='course-search',prop=isCourse?'search':'dictSearch';ui[prop]=ev.target.value;const start=ev.target.selectionStart,end=ev.target.selectionEnd,id=ev.target.id;render();const input=$('#'+id);if(input){input.focus();input.setSelectionRange(start,end);}return;}if(ev.target.id==='role-input'&&ui.quiz){ui.quiz.roleAnswer=ev.target.value;}});
app.addEventListener('change',ev=>{if(ev.target.id==='dict-level'){ui.dictLevel=ev.target.value;ui.showMoreWords=false;render();}else if(ev.target.id==='import-file'){importData(ev.target.files?.[0]);ev.target.value='';}});
window.addEventListener('hashchange',()=>{ui.navOpen=false;ui.quiz=null;ui.dialogTranslations=false;ui.showMoreWords=false;const r=route(),q=r.match(/^course\?level=(A0|A1|A2|B1|B2)$/);if(q){ui.level=q[1];}render(true);});
app.addEventListener('click',ev=>{const a=ev.target.closest('a[data-level-link]');if(a){ui.level=a.dataset.level;}});
if(!location.hash)history.replaceState(null,'','#/home');
render();
if('serviceWorker'in navigator&&location.protocol.startsWith('http')){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
window.SrpskiLabDebug={modules,lessons,dictionary,buildLessonQuestions,buildExamQuestions,romanToCyr,cyrToRoman,state};
})();
