import{useEffect,useState}from 'react';
import{Link,useNavigate,useParams}from 'react-router-dom';
import{ArrowLeft,ArrowRight,GraduationCap,CheckCircle2,LockKeyhole,XCircle,RotateCcw}from 'lucide-react';
import{PageHead,Meter}from '../components/Layout';
import{useProgress}from '../lib/session';
import{examQuestions,levelNames,levels,levelLessons,chooseScript}from '../lib/catalog';
import{canStartExam}from '../lib/access';
import type{AttemptResult,Level}from '../lib/types';
export default function Exams(){const params=useParams(),selected=params.level?.toUpperCase() as Level|undefined;
 const{lessons:progress,exams,profile,submitExam}=useProgress();const navigate=useNavigate();
 const[answers,setAnswers]=useState<Record<string,string>>({}),[index,setIndex]=useState(0),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<AttemptResult|null>(null),[error,setError]=useState('');
 useEffect(()=>{setAnswers({});setIndex(0);setValue('');setBusy(false);setResult(null);setError('')},[selected]);
 const script=profile?.script||'latin';const valid=Boolean(selected&&levels.includes(selected));
 if(!valid)return <><PageHead eyebrow="КОНТРОЛЬ ЗНАНИЙ" title="Экзамены по уровням" description="Экзамен открывается после завершения всех уроков своего уровня. Для зачёта необходимо 80%." icon={GraduationCap}/><div className="exam-list">{levels.map(l=>{const total=levelLessons(l).length,done=levelLessons(l).filter(x=>progress[x.id]?.status==='completed').length,passed=exams.find(e=>e.level===l&&e.passed),available=canStartExam(l,progress);return <div className="panel exam-list-row" key={l}><span className="exam-symbol"><GraduationCap size={24}/></span><div><span className="tag">{l}</span><h2>{levelNames[l]}</h2><p>{done} из {total} уроков пройдено · 20 вопросов</p><Meter value={done/total*100}/></div>{passed?<Link className="button button-secondary" to={`/exam/${l}`}><CheckCircle2 size={18}/> Пройден · {passed.score}%</Link>:available?<Link className="button button-primary" to={`/exam/${l}`}>Начать <ArrowRight size={18}/></Link>:<span className="exam-locked"><LockKeyhole size={17}/> Недоступен</span>}</div>})}</div><div className="callout"><GraduationCap size={24}/><div><b>Учебный экзамен ≠ официальный сертификат</b><p>Баллы отражают результат внутри платформы. Для подтверждения уровня B1/B2 отдельно нужна проверка разговорной речи, письма и аудирования.</p></div></div></>;
 const level=selected as Level;const qs=examQuestions[level],done=canStartExam(level,progress),q=qs[index];
 if(!done)return <div className="panel locked-page"><LockKeyhole size={44}/><h1>Экзамен {selected} пока закрыт</h1><p>Сначала заверши все уроки уровня {selected}. Затем сможешь проверить знания и открыть следующий уровень.</p><Link className="button button-primary" to={`/course/${selected}`}>К урокам уровня <ArrowRight size={18}/></Link></div>;
 function answerCurrent(){if(!value.trim())return;setAnswers(a=>({...a,[q.id]:value.trim()}));setValue('');setIndex(i=>Math.min(i+1,19))}
 async function finish(){setBusy(true);setError('');try{const r=await submitExam(selected!,answers,crypto.randomUUID());setResult(r)}catch(e){setError(String(e))}finally{setBusy(false)}}
 function restart(){setAnswers({});setIndex(0);setValue('');setResult(null);setError('')}
 return <><div className="lesson-breadcrumb"><button className="back-button" onClick={()=>navigate('/exams')}><ArrowLeft size={17}/> Экзамены</button></div><div className="lesson-header"><span className="tag green">ЭКЗАМЕН · {selected}</span><h1>Проверка уровня {selected}</h1><p>{selected ? levelNames[selected] : ''}. 20 вопросов по материалам программы. Проходной порог — 80%.</p></div><div className="panel exam-quiz">{result?<><div className={`result-card ${result.passed?'passed':'failed'}`}>{result.passed?<CheckCircle2 size={52}/>:<XCircle size={52}/>}<div className="result-score">{result.score}%</div><h2>{result.passed?'Экзамен сдан!':'Экзамен не сдан'}</h2><p>{result.passed?'Зачёт подтверждён в твоём аккаунте.': 'Для перехода на следующий уровень необходимо не менее 80%.'}</p></div><div className="feedback-list">{result.feedback.map((a,i)=><div className={`feedback ${a.correct?'correct':'wrong'}`} key={a.id}><div>{a.correct?<CheckCircle2 size={19}/>:<XCircle size={19}/>}<b>Вопрос {i+1}</b></div>{!a.correct&&<><p>Твой ответ: {a.yourAnswer}</p><small>Правильный ответ: {a.answer}</small></>}</div>)}</div><div className="lesson-actions"><button className="button button-secondary" onClick={restart}><RotateCcw size={17}/> Попробовать снова</button><Link className="button button-primary" to="/course">Вернуться к курсу</Link></div></>:<><div className="quiz-top"><h2>Вопросы экзамена</h2><span className="tag green">{Object.keys(answers).length} / 20</span></div><Meter value={Object.keys(answers).length/20*100}/>{Object.keys(answers).length<20?<div className="question-card"><span className="eyebrow">ВОПРОС {index+1} ИЗ 20</span><h3>{chooseScript(q.prompt,script)}</h3><div className="choice-grid">{q.options.map((option,i)=><button className={`choice ${value===option?'chosen':''}`} key={i} onClick={()=>setValue(option)}><span className="choice-letter">{String.fromCharCode(65+i)}</span>{chooseScript(option,script)}</button>)}</div><button className="button button-primary" disabled={!value} onClick={answerCurrent}>Следующий вопрос <ArrowRight size={17}/></button></div>:<div className="question-card centered"><GraduationCap size={45}/><h3>Ты ответил на все вопросы</h3><p>Теперь отправь экзамен на проверку. Результат сохранится в твоём аккаунте.</p><button className="button button-primary" disabled={busy} onClick={()=>void finish()}>{busy?'Проверяем…':'Проверить экзамен'} <ArrowRight size={17}/></button></div>}</>}{error&&<div className="form-error" role="alert">{error}</div>}</div></>;
}
