import{Link}from 'react-router-dom';
import type{ReactNode}from 'react';
import{ArrowRight,BookOpen,Flame,Layers,Target,MessageCircle}from 'lucide-react';
import{useProgress}from '../lib/session';
import{chooseScript,levels,levelNames,LEVEL_COLORS,lessons,levelLessons}from '../lib/catalog';
import {
  nextLesson,
  completionPercent,
  lessonStatus
} from '../lib/access';
import{Meter}from '../components/Layout';
export default function Home(){const{profile,lessons:progress,exams,words}=useProgress();const script=profile?.script||'latin';const next=nextLesson(progress,exams),count=lessons.filter(l=>lessonStatus(l,progress,exams)==='completed').length;
 const due=Object.values(words).filter(w=>new Date(w.due_at).getTime()<=Date.now()).length;
 const examsPassed=levels.filter(l=>exams.some(e=>e.level===l&&e.passed));
 const weekdayData=Array.from({length:7},(_,i)=>{const day=new Date();day.setDate(day.getDate()-(6-i));return{date:day.toLocaleDateString('ru-RU',{weekday:'short'}),done:Object.values(progress).filter(p=>p.completed_at&&new Date(p.completed_at).toLocaleDateString()===day.toLocaleDateString()).length}});
 return <><section className="hero"><div className="hero-content"><div className="eyebrow light">ТВОЁ ПРОСТРАНСТВО ДЛЯ ЯЗЫКА ———</div><h1>Dobar dan, {profile?.display_name||'друг'}! 👋</h1><p>От первых <i>zdravo</i> до свободных разговоров в Нови-Саде. Маленький шаг каждый день — и сербский становится своим.</p><div className="hero-actions"><Link to={`/lesson/${next.id}`} className="button button-inverted"><BookOpen size={18}/>{count?'Продолжить обучение':'Начать первый урок'}</Link><Link to="/course" className="button button-ghost">Посмотреть программу <ArrowRight size={17}/></Link></div></div><div className="hero-graphic"><span className="round round-a"></span><span className="round round-b"></span><span className="hero-letter">Ђ</span><span className="hero-chip one">Zdravo!</span><span className="hero-chip two">Хвала ♡</span></div></section>
 <div className="stat-row"><Stat icon={<BookOpen/>}tone="green"value={count}suffix={` / ${lessons.length}`}label="Пройдено уроков"hint={<Meter value={completionPercent(undefined,progress)}/>}/><Stat icon={<Flame/>}tone="orange"value={new Set(Object.values(progress).filter(p=>p.completed_at).map(p=>p.completed_at!.slice(0,10))).size}label="Дней с пройденными уроками"hint="За всё время"/><Stat icon={<Layers/>}tone="blue"value={Object.keys(words).length}label="Слов в повторении"hint={`Сегодня к повторению: ${due}`}/><Stat icon={<Target/>}tone="purple"value={examsPassed.length}suffix=" / 5" label="Экзаменов пройдено"hint={<Meter value={examsPassed.length*20}/>}/></div>
 <div className="two-col"><section className="panel next-panel"><div className="eyebrow">ТВОЙ СЛЕДУЮЩИЙ ШАГ</div><div className="next-panel-header"><h2>{count?'Продолжай в том же духе!':'Всё начинается сегодня'}</h2><span className="tag green">{next.level} · Урок {next.order}</span></div><h3>{chooseScript(next.title,script)}</h3><p>{next.note}</p><div className="tiny-row"><span>◷ 30–40 минут</span><span>▤ Две азбуки и первые звуки</span></div><Link to={`/lesson/${next.id}`} className="button button-primary fill">{count?'Продолжить урок':'Открыть урок'} <ArrowRight size={18}/></Link></section>
 <section className="panel review-panel"><div className="eyebrow">ИНТЕРВАЛЬНОЕ ПОВТОРЕНИЕ</div><h2>Слова в памяти</h2><strong className="stat-giant">{due}</strong><span className="muted">слов ждут повторения</span><p>Карточки возвращаются через 1, 3, 7, 14 и 30 дней. Повторяй то, что действительно изучил.</p><Link to="/review" className="button button-mint fill">Открыть карточки <ArrowRight size={17}/></Link></section></div>
 <section className="roadmap-section"><div className="section-heading"><div><div className="eyebrow">ТВОЯ ДОРОЖНАЯ КАРТА</div><h2>Пять уровней, одна большая цель</h2></div><Link to="/course">Вся программа <ArrowRight size={17}/></Link></div><div className="level-grid">{levels.map(level=>{const total=levelLessons(level).length,done=levelLessons(level).filter(l=>progress[l.id]?.status==='completed').length;return <Link to={`/course/${level}`} className="level-card" key={level}><span className="level-badge" style={{background:LEVEL_COLORS[level]}}>{level}</span><b>{levelNames[level]}</b><p>{({A0:'Алфавит и первые диалоги',A1:'Семья, город, еда и дом',A2:'Падежи, документы и телефон',B1:'Работа, планы и аргументы',B2:'Дискуссии и профессиональный язык'}as Record<string,string>)[level]}</p><div className="level-footer"><small>{done} / {total} уроков</small><strong>{Math.round(done/total*100)}%</strong></div><Meter value={done/total*100}/></Link>})}</div></section>
 <section className="tip"><MessageCircle size={24}/><div><strong>Язык начинается за пределами учебника</strong><p>Попробуй сегодня поздороваться, уточнить цену или задать короткий вопрос по-сербски.</p></div><Link to="/course">Практика для жизни <ArrowRight size={17}/></Link></section>
 {weekdayData.length>0&&<section className="panel activity"><div className="section-heading"><h2>Твоя учебная неделя</h2><span className="muted">Уроки, завершённые по дням</span></div><div className="week-bars">{weekdayData.map((d,i)=><div key={i} className="week-day"><div style={{height:`${Math.max(10,d.done*28)}px`}} className={d.done?'active':''}/><small>{d.date}</small></div>)}</div></section>}
 </>;
}
function Stat({icon,tone,value,suffix='',label,hint}:{icon:ReactNode,tone:string,value:number,suffix?:string,label:string,hint:ReactNode}){return <div className="stat-card"><span className={`stat-icon ${tone}`}>{icon}</span><div className="stat-value">{value}<small>{suffix}</small></div><p>{label}</p><div className="stat-hint">{hint}</div></div>}
