import{useEffect,useMemo,useRef,useState}from 'react';
import{Link,useNavigate,useParams}from 'react-router-dom';
import{ArrowLeft,ArrowRight,BookOpen,BookText,Check,CheckCircle2,Headphones,LockKeyhole,RotateCcw,Send,Volume2,WifiOff,XCircle}from 'lucide-react';
import{useAuth,useProgress}from '../lib/session';
import{canOpenLesson}from '../lib/access';
import{alphabet,chooseScript,lessonById,lessons,lessonIndex}from '../lib/catalog';
import{AudioButton}from '../components/AudioButton';
import{Meter,Empty}from '../components/Layout';
import type{AttemptResult}from '../lib/types';
const steps=['theory','vocabulary','dialogue','practice','quiz','result']as const;
const names=['Теория','Слова','Диалог','Практика','Тест','Результат'];
type Step=typeof steps[number];
export default function Lesson(){const{id}=useParams(),navigate=useNavigate();const lesson=id?lessonById.get(id):null;
 const{user}=useAuth(),{lessons:progress,exams,loading,saveStep,markWords,submitLesson}=useProgress();
 const [step,setStep]=useState<Step>('theory');const [answers,setAnswers]=useState<Record<string,string>>({});
 const[index,setIndex]=useState(0),[value,setValue]=useState(''),[result,setResult]=useState<AttemptResult|null>(null),[pending,setPending]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showTranslations,setShowTranslations]=useState(false),[roleAnswer,setRoleAnswer]=useState('');
 const script=useProgress().profile?.script||'latin';
 const restored=useRef<string|null>(null);
 useEffect(()=>{setStep('theory');setAnswers({});setIndex(0);setValue('');setResult(null);setPending(false);setError('');setShowTranslations(false);setRoleAnswer('')},[id]);
 useEffect(()=>{if(id&&!loading&&restored.current!==id){restored.current=id;const old=progress[id]?.last_step;const safeStep=(old&&steps.includes(old as Step)&&old!=='result'?old:'theory')as Step;setStep(safeStep)}},[id,loading,progress]);
 const accessible=lesson?canOpenLesson(lesson,progress,exams):false;
 const next=useMemo(()=>{if(!lesson)return null;return lessons[(lessonIndex.get(lesson.id)??0)+1]||null},[lesson]);
 if(!lesson)return <Empty title="Урок не найден" description="Возможно, ссылка устарела. Вернись в программу."/>;
 if(loading)return <div className="panel wait">Загружаю твой прогресс…</div>;
 if(!user)return <div className="panel locked-page"><LockKeyhole size={36}/><h1>Войди, чтобы начать обучение</h1><p>Для сохранения результатов и разблокировки следующих уроков нужен аккаунт.</p><Link className="button button-primary" to="/auth/sign-up">Создать аккаунт <ArrowRight size={18}/></Link></div>;
 if(!accessible){const prev=lessons[(lessonIndex.get(lesson.id)??1)-1];return <div className="panel locked-page"><LockKeyhole size={44}/><span className="eyebrow">УРОК {lesson.order} · {lesson.level}</span><h1>Этот урок пока закрыт</h1><p>Чтобы начать «{lesson.title}», сначала успешно пройди предыдущий урок{prev?` «${prev.title}»`:''}. Нужно минимум 70% на проверочном тесте, а на границе уровней — 80% на экзамене.</p><Link className="button button-primary" to={prev?`/lesson/${prev.id}`:'/course'}>Перейти к предыдущему уроку <ArrowRight size={18}/></Link></div>}
 const question=lesson.questions[index];
 async function changeStep(s:Step){if(s==='result'&&!result&&!pending)return;setStep(s);setError('');if(s==='vocabulary')void markWords(lesson!.vocab.map(w=>w.id)).catch(e=>setError(String(e)));try{await saveStep(lesson!.id,s)}catch{/* state already reported on top bar */}}
 async function onSubmit(){if(busy||Object.keys(answers).length!==lesson!.questions.length)return;setBusy(true);setError('');try{
  const attemptKey=crypto.randomUUID();const response=await submitLesson(lesson!.id,answers,attemptKey);
  if('queued'in response){setPending(true);setResult(null)}else{setResult(response);setPending(false)}
  setStep('result');
 }catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function answerCurrent(){if(!value.trim())return;setAnswers(old=>({...old,[question.id]:value.trim()}));setIndex(i=>Math.min(i+1,lesson!.questions.length-1));setValue('')}
 function restart(){setStep('quiz');setAnswers({});setIndex(0);setValue('');setResult(null);setPending(false);setError('')}
 const answerCount=Object.keys(answers).length;
 return <><div className="lesson-breadcrumb"><Link to="/course"><ArrowLeft size={16}/> Все уроки</Link><span>/</span><span>{lesson.level}</span><span>/</span><strong>Урок {lesson.order}</strong></div>
 <div className="lesson-header"><span className="tag green">УРОВЕНЬ {lesson.level} · УРОК {lesson.order} ИЗ 265</span><h1>{chooseScript(lesson.title,script)}</h1><p>{lesson.note}</p><div className="lesson-meta"><span>◷ 30–40 минут</span><span>♫ Сербское аудио</span><span>✓ Зачёт от 70%</span></div></div>
 <div className="lesson-steps">{steps.map((s,i)=><button key={s} className={`${step===s?'selected':''} ${i<steps.indexOf(step)?'past':''}`} disabled={s==='result'&&!result&&!pending} onClick={()=>void changeStep(s)}><span>{i<steps.indexOf(step)?<Check size={14}/>:i+1}</span><b>{names[i]}</b></button>)}</div>
 <div className="panel lesson-body">
 {step==='theory'&&<><div className="eyebrow">ШАГ 1 / 6 · РАЗБИРАЕМСЯ В ТЕМЕ</div><h2>{chooseScript(lesson.title,script)}</h2><p className="long-copy">{lesson.note}</p><div className="callout"><BookOpen size={22}/><div><b>Цель урока</b><p>Разобраться в теме «{lesson.title}», прочитать примеры, использовать слова в диалоге и подтвердить результат в тесте.</p></div></div><h3>Примеры из повседневной речи</h3><div className="example-list">{lesson.examples.map((e,i)=><div className="example" key={i}><AudioButton text={e.sr}/><span><b>{chooseScript(e.sr,script)}</b><small>{e.ru}</small></span></div>)}</div>{lesson.moduleId===1&&<><h3>Сербский алфавит: латиница и кириллица</h3><div className="alphabet-grid">{alphabet.map(([latin,cyr,hint])=><div className="alphabet-cell" key={latin}><b>{latin}</b><strong>{cyr}</strong><small>{hint}</small></div>)}</div></>}
 {lesson.addon&&<><h3>{lesson.addon[0]}</h3><p className="long-copy">{lesson.addon[1]}</p><div className="example-list">{lesson.addon[2].map(([sr,ru],i)=><div className="example" key={i}><AudioButton text={sr}/><span><b>{chooseScript(sr,script)}</b><small>{ru}</small></span></div>)}</div></>}
 <p className="minor-note">Обрати внимание: некоторые примеры повторяются между уроками одного модуля — это материал исходной версии. Содержание B1/B2 требует дополнительной педагогической редакции.</p></>}
 {step==='vocabulary'&&<><div className="eyebrow">ШАГ 2 / 6 · ЗАПОМИНАЕМ СЛОВА</div><h2>Словарь урока</h2><p className="muted">Слушай произношение, читай вслух и возвращайся к новым словам в разделе «Повторение».</p><div className="vocab-list">{lesson.vocab.map((w,i)=><div className="vocab-row" key={`${w.id}-${i}`}><span className="word-num">{String(i+1).padStart(2,'0')}</span><div className="word-primary"><b>{chooseScript(w.sr,script)}</b>{w.usage&&<small>{chooseScript(w.usage,script)} <AudioButton text={w.usage} small/></small>}</div><span className="word-ru">{w.ru}</span><AudioButton text={w.sr}/></div>)}</div><div className="callout mint"><Headphones size={24}/><div><b>Как слушать?</b><p>Нажми значок динамика рядом со словом. Скорость воспроизведения меняется в верхней панели.</p></div></div></>}
 {step==='dialogue'&&<><div className="eyebrow">ШАГ 3 / 6 · ЖИВОЙ СЕРБСКИЙ</div><h2>Диалог из жизни</h2><p className="muted">Попробуй сначала понять диалог без перевода, затем проверь себя.</p><div className="dialogue-thread">{lesson.dialogue.map((d,i)=><div className={`bubble-wrap ${i%2?'self':''}`} key={i}><span className="bubble-speaker">{d.by}</span><div className="bubble"><AudioButton text={d.sr} small/><div><b>{chooseScript(d.sr,script)}</b>{showTranslations&&<small>{d.ru}</small>}</div></div></div>)}</div><button className="button button-secondary" onClick={()=>setShowTranslations(s=>!s)}>{showTranslations?'Скрыть перевод':'Показать перевод'}</button></>}
 {step==='practice'&&<><div className="eyebrow">ШАГ 4 / 6 · ФОРМУЛИРУЕМ САМИ</div><h2>Попробуй сказать сам</h2><p>Представь, что ты оказался в Нови-Саде и тебе нужно использовать тему «{lesson.title}». Составь короткую фразу по-сербски, используя слова из урока.</p><label className="form-label" htmlFor="roleanswer">Твоя фраза на сербском</label><textarea id="roleanswer" className="form-control textarea" value={roleAnswer} onChange={e=>setRoleAnswer(e.target.value)} placeholder="Напиши свой вариант…"/><div className="callout"><BookText size={24}/><div><b>Проверка свободной речи</b><p>На этом этапе текст сохраняется только до закрытия занятия. ИИ не проверяет свободные ответы: сравни их с примерами выше и попроси преподавателя оценить правильность.</p></div></div></>}
 {step==='quiz'&&<><div className="eyebrow">ШАГ 5 / 6 · КОНТРОЛЬ ЗНАНИЙ</div><div className="quiz-top"><h2>Проверочный тест</h2><span className="tag green">{answerCount}/7 ответов</span></div><Meter value={answerCount/7*100}/><p className="muted">Порог прохождения — 70%. Новый урок откроется только после проверки на сервере.</p>
  {answerCount<lesson.questions.length?<div className="question-card" key={question.id}><span className="eyebrow">ВОПРОС {index+1} ИЗ 7</span><h3>{chooseScript(question.prompt,script)}</h3>{question.kind==='choice'?<div className="choice-grid">{question.options.map((choice,i)=><button key={choice+i} className={`choice ${value===choice?'chosen':''}`} onClick={()=>setValue(choice)}><span className="choice-letter">{String.fromCharCode(65+i)}</span>{chooseScript(choice,script)}</button>)}</div>:<div><label className="form-label" htmlFor="answer-input">Введи ответ</label><input className="form-control" id="answer-input" autoComplete="off" placeholder="Напиши свой ответ…" value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')answerCurrent()}}/></div>}<button className="button button-primary" disabled={!value.trim()} onClick={answerCurrent}>{index+1===7?'Записать последний ответ':'Следующий вопрос'} <ArrowRight size={18}/></button></div>:<div className="question-card centered"><CheckCircle2 size={45} color="#258b6c"/><h3>Все ответы записаны</h3><p>Нажми «Отправить на проверку», чтобы получить результат и, если баллов достаточно, открыть следующий урок.</p><button className="button button-primary" disabled={busy} onClick={()=>void onSubmit()}><Send size={17}/>{busy?'Проверяем…':'Отправить на проверку'}</button></div>}
 </>}
 {step==='result'&&(result||pending)&&<><div className="eyebrow">ШАГ 6 / 6 · РЕЗУЛЬТАТ</div>{pending?<div className="result-card waiting"><WifiOff size={50}/><h2>Ожидает синхронизации</h2><p>Нет связи с сервером. Мы сохранили попытку на этом устройстве. Следующий урок не разблокируется, пока результат не будет проверен в облаке.</p></div>:result&&<><div className={`result-card ${result.passed?'passed':'failed'}`}>{result.passed?<CheckCircle2 size={54}/>:<XCircle size={54}/>}<div className="result-score">{result.score}%</div><h2>{result.passed?'Урок успешно пройден!':'Нужно немного потренироваться'}</h2><p>{result.passed?'Результат подтверждён сервером и сохранён в твоём профиле.':'Для зачёта требуется минимум 70%. Ты можешь повторить тест без ограничений.'}</p></div><h3>Разбор ответов</h3><div className="feedback-list">{result.feedback.map((f,i)=><div key={f.id} className={`feedback ${f.correct?'correct':'wrong'}`}><div>{f.correct?<CheckCircle2 size={20}/>:<XCircle size={20}/>}<b>Вопрос {i+1}</b></div><p>Твой ответ: {f.yourAnswer}</p>{!f.correct&&<small>Правильно: {f.answer}</small>}</div>)}</div></>}
  <div className="lesson-actions"><button className="button button-secondary" onClick={restart}><RotateCcw size={17}/> Повторить тест</button>{result?.passed&&next?<button className="button button-primary" onClick={()=>navigate(`/lesson/${next.id}`)}>Следующий урок <ArrowRight size={18}/></button>:null}{result?.passed&&!next?<Link className="button button-primary" to="/progress">Мой прогресс</Link>:null}</div>
 </>}
 {error&&<div className="form-error" role="alert">{error}</div>}
 {step!=='result'&&step!=='quiz'&&<div className="lesson-actions"><button className="button button-secondary" disabled={step==='theory'} onClick={()=>void changeStep(steps[Math.max(0,steps.indexOf(step)-1)])}><ArrowLeft size={17}/> Назад</button><button className="button button-primary" onClick={()=>void changeStep(steps[steps.indexOf(step)+1])}>{step==='practice'?'Перейти к тесту':'Дальше'} <ArrowRight size={18}/></button></div>}
 </div><div className="lesson-end-note"><Volume2 size={18}/> Голос в базовом пакете синтетический. Для эталонной фонетики дополнительно сверяй произношение с носителями.</div>
 </>;
}
