import{useEffect,useState}from 'react';
import{Activity,BarChart3,BookOpen,CheckCircle2,Flame,Layers}from 'lucide-react';
import{useProgress}from '../lib/session';
import{getSupabase,errorMessage}from '../lib/supabase';
import{levels,levelNames,levelLessons,lessons}from '../lib/catalog';
import{PageHead,Meter}from '../components/Layout';
import{useAuth}from '../lib/session';
type Attempt={lesson_id:string,score:number,passed:boolean,submitted_at:string};
export default function Progress(){const{user}=useAuth();const{lessons:done,exams,words,legacy}=useProgress();const[attempts,setAttempts]=useState<Attempt[]>([]),[error,setError]=useState('');
 useEffect(()=>{let alive=true;if(user)getSupabase().from('lesson_attempts').select('lesson_id,score,passed,submitted_at').eq('user_id',user.id).order('submitted_at',{ascending:false}).limit(60).then(({data,error})=>{if(alive){if(error)setError(errorMessage(error));else setAttempts(data||[])}});return()=>{alive=false}},[user]);
 const completed=Object.values(done).filter(p=>p.status==='completed'),due=Object.values(words).filter(w=>new Date(w.due_at)<=new Date()),days=new Set(completed.map(p=>p.completed_at?.slice(0,10)).filter(Boolean));
 const latest=attempts.slice(0,15),wrong=attempts.filter(a=>!a.passed).length;
 return <><PageHead eyebrow="ТВОЙ КАБИНЕТ" title="Мой прогресс" description="Все результаты сохранены на сервере и доступны после входа с другого устройства." icon={BarChart3}/><div className="stat-row"><div className="stat-card"><span className="stat-icon green"><BookOpen/></span><div className="stat-value">{completed.length}<small> / {lessons.length}</small></div><p>Уроков завершено</p><Meter value={completed.length/lessons.length*100}/></div><div className="stat-card"><span className="stat-icon orange"><Flame/></span><div className="stat-value">{days.size}</div><p>Дней с успешными уроками</p></div><div className="stat-card"><span className="stat-icon purple"><Layers/></span><div className="stat-value">{Object.keys(words).length}</div><p>Слов в карточках · {due.length} к повторению</p></div><div className="stat-card"><span className="stat-icon blue"><CheckCircle2/></span><div className="stat-value">{exams.filter(e=>e.passed).length}</div><p>Зачтённых попыток экзаменов</p></div></div>
 <div className="two-col"><div className="panel"><div className="eyebrow">УСПЕШНОСТЬ ПО УРОВНЯМ</div><h2>Твоя программа</h2>{levels.map(l=>{const ls=levelLessons(l),n=ls.filter(x=>done[x.id]?.status==='completed').length;return <div className="progress-level" key={l}><div><span className="tag green">{l}</span><b>{levelNames[l]}</b><small>{n}/{ls.length}</small></div><Meter value={n/ls.length*100}/></div>})}</div>
 <div className="panel"><div className="eyebrow">ТВОЯ АКТИВНОСТЬ</div><h2>Чего удалось достичь</h2><div className="highlight-row"><Activity size={22}/><div><b>{attempts.length}</b><small>последних загруженных попыток тестов</small></div></div><div className="highlight-row"><BarChart3 size={22}/><div><b>{wrong}</b><small>неудачных попыток среди загруженных</small></div></div><div className="highlight-row"><Layers size={22}/><div><b>{Object.values(words).filter(w=>w.stage>=3).length}</b><small>слов на стадии уверенного повторения</small></div></div><div className="highlight-row"><BookOpen size={22}/><div><b>{legacy.filter(l=>l.legacy_done).length}</b><small>исторических записей, импортированных без верификации</small></div></div></div></div>
 <section className="panel"><div className="eyebrow">ИСТОРИЯ ЗАНЯТИЙ</div><h2>Последние тесты</h2>{latest.length?<div className="history-list">{latest.map((a,i)=><div key={`${a.lesson_id}${i}`} className="history-row"><span className={a.passed?'history-ok':'history-bad'}>{a.passed?'✓':'!'}</span><div><b>Урок {a.lesson_id}</b><small>{new Date(a.submitted_at).toLocaleString('ru-RU')}</small></div><strong>{a.score}%</strong></div>)}</div>:<p className="muted">Пока нет завершённых тестов.</p>}{error&&<div className="form-error">{error}</div>}</section>
 <div className="callout mint"><CheckCircle2 size={23}/><div><b>Подтверждённый и импортированный прогресс — разные вещи</b><p>Результаты из старого JSON сохраняются отдельно как история; без проверяемой подписи они не открывают заблокированные уроки автоматически. Пройди соответствующий тест заново, чтобы получить серверный зачёт.</p></div></div></>;
}
