import{useMemo,useState}from 'react';
import{BookOpen,RotateCcw,CheckCircle2,Layers,Eye,Volume2}from 'lucide-react';
import{useProgress}from '../lib/session';
import{dictionaryById,chooseScript}from '../lib/catalog';
import{AudioButton}from '../components/AudioButton';
import{PageHead,Empty}from '../components/Layout';
export default function Review(){const{profile,words,reviewWord}=useProgress(),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[errors,setErrors]=useState('');
 const due=useMemo(()=>Object.values(words).filter(w=>new Date(w.due_at).getTime()<=Date.now()).sort((a,b)=>new Date(a.due_at).getTime()-new Date(b.due_at).getTime()),[words]);
 const top=due[0],w=top?dictionaryById.get(top.word_id):null;
 const script=profile?.script||'latin';async function rate(grade:string){if(!w||busy)return;setBusy(true);setErrors('');try{await reviewWord(w.id,grade,crypto.randomUUID());setShow(false)}catch(e){setErrors(String(e))}finally{setBusy(false)}}
 return <><PageHead eyebrow="ИНТЕРВАЛЬНОЕ ПОВТОРЕНИЕ" title="Запоминай надолго" description="Вспомни перевод до подсказки, затем честно оцени, насколько легко он дался." icon={Layers}/><div className="panel review-stage"><div className="review-meta"><span className="tag green">Сегодня: {due.length} слов</span><span className="muted">Всего в карточках: {Object.keys(words).length}</span></div>{!w?<Empty icon={CheckCircle2} title="На сегодня всё!" description="Пока нет слов для повторения. Пройди новый урок или добавь слова из словаря."/>:<><div className="flashcard"><span className="eyebrow">ПЕРЕВЕДИ НА РУССКИЙ</span><AudioButton text={w.sr}/><h2>{chooseScript(w.sr,script)}</h2>{w.usage&&<p>{chooseScript(w.usage,script)}</p>}{show?<div className="flash-answer"><span>Правильный перевод</span><h3>{w.ru}</h3></div>:<button className="button button-secondary" onClick={()=>setShow(true)}><Eye size={17}/> Показать ответ</button>}</div>{show&&<div className="grade-actions"><button disabled={busy} className="grade again" onClick={()=>void rate('again')}><RotateCcw size={18}/>Не помню<small>Ещё раз</small></button><button disabled={busy} className="grade hard" onClick={()=>void rate('hard')}>Трудно<small>Короткий интервал</small></button><button disabled={busy} className="grade good" onClick={()=>void rate('good')}>Хорошо<small>По расписанию</small></button><button disabled={busy} className="grade easy" onClick={()=>void rate('easy')}>Легко<small>Ускоренное повторение</small></button></div>}</>}{errors&&<div className="form-error">{errors}</div>}</div>
 <div className="callout mint"><Volume2 size={25}/><div><b>Помни о произношении</b><p>Прослушивай слова на сербском. Проверка собственного произношения пока не автоматизирована.</p></div></div><div className="callout"><BookOpen size={23}/><div><b>Интервалы повторения</b><p>1, 3, 7, 14 и 30 дней. Ошибка возвращает слово к короткому интервалу, но не удаляет его из словаря.</p></div></div></>;
}
