import{useState,type ChangeEvent}from 'react';
import{Link}from 'react-router-dom';
import{Cloud,Download,Upload,Settings as SettingsIcon,ShieldCheck,AlertTriangle,Trash2,Volume2,UserRound,KeyRound,Mail}from 'lucide-react';
import{PageHead}from '../components/Layout';
import{useAuth,useProgress}from '../lib/session';
import{getSupabase,errorMessage}from '../lib/supabase';
import{useVoice}from '../lib/voice';
import{audioUrl}from '../lib/audio';
export default function Settings(){const{user,signOut}=useAuth();const{profile,lessons,exams,words,legacy,saveProfile,importLegacy,refresh}=useProgress();
 const[name,setName]=useState<string|undefined>(undefined),[script,setScript]=useState<string|undefined>(undefined),[theme,setTheme]=useState<string|undefined>(undefined),[goal,setGoal]=useState<number|undefined>(undefined);
 const[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[password,setPassword]=useState('');const{play,status,rate,setRate}=useVoice();
 const n=name??profile?.display_name??'Ученик',s=script??profile?.script??'latin',t=theme??profile?.theme??'light',g=goal??profile?.daily_goal??1;
 async function store(){setBusy(true);setError('');try{await saveProfile(n,s,t,g);setMessage('Настройки сохранены в облаке.')}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 function download(){const payload={exportVersion:2,exportedAt:new Date().toISOString(),profile:{...profile},lesson_progress:lessons,exam_attempts:exams,user_word_progress:words,legacy_imported_progress:legacy};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`srpskilab-cloud-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
 async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');setMessage('');try{
  if(file.size>2_000_000)throw Error('Слишком большой JSON (лимит 2 МБ)');const raw=await file.text();const data=JSON.parse(raw);
  if(data.version!==1||!data.lessons||typeof data.lessons!=='object'||Array.isArray(data.lessons))throw Error('Выбери экспорт старой версии SrpskiLab (version: 1).');
  const lessonMap=data.lessons as Record<string,unknown>;
  const sha=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));const hash=[...new Uint8Array(sha)].map(n=>n.toString(16).padStart(2,'0')).join('');
  if(!window.confirm(`Найдено ${Object.keys(lessonMap).length} записей из старого курса. Они сохранятся как исторические (непроверенные) и не обойдут разблокировку. Импортировать?`))return;
  const summary=await importLegacy(hash,data);setMessage(summary.duplicate?'Этот файл уже был импортирован.':`Импортировано: ${summary.count} записей уроков, ${summary.exams} экзаменов и ${summary.words} слов.`);
 }catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function changePassword(){if(password.length<8){setError('Пароль должен содержать не менее 8 символов.');return}setBusy(true);try{const{error}=await getSupabase().auth.updateUser({password});if(error)throw error;setPassword('');setMessage('Пароль изменён.')}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function deleteAccount(){if(!window.confirm('Удалить аккаунт и всю связанную историю обучения без возможности восстановления? Перед удалением скачай резервную копию.'))return;
  const typed=window.prompt('Для подтверждения введи УДАЛИТЬ');if(typed!=='УДАЛИТЬ')return;
  setBusy(true);setError('');try{const{error}=await getSupabase().functions.invoke('delete-account',{body:{confirm:'УДАЛИТЬ'}});if(error)throw error;await signOut();window.location.assign('/');}catch(e){setError(`Удаление не выполнено: ${errorMessage(e)}. Убедись, что Edge Function delete-account опубликована.`)}finally{setBusy(false)}}
 return <><PageHead eyebrow="ТВОЙ КАБИНЕТ" title="Настройки" description="Личные данные, удобный формат занятий, экспорт прогресса и проверка озвучки." icon={SettingsIcon}/><div className="two-col settings-panels"><section className="panel"><h2><UserRound size={22}/> Мой профиль</h2><label className="form-label">Как к тебе обращаться<input className="form-control" maxLength={60} value={n} onChange={e=>setName(e.target.value)}/></label><label className="form-label">Письменность<select className="form-control" value={s} onChange={e=>setScript(e.target.value)}><option value="latin">Latinica — Zdravo</option><option value="cyrillic">Ћирилица — Здраво</option></select></label><label className="form-label">Тема оформления<select className="form-control" value={t} onChange={e=>setTheme(e.target.value)}><option value="light">Светлая</option><option value="dark">Тёмная</option><option value="system">Как в системе</option></select></label><label className="form-label">Цель — уроков в день<select className="form-control" value={g} onChange={e=>setGoal(Number(e.target.value))}>{Array.from({length:10},(_,i)=>i+1).map(x=><option key={x} value={x}>{x}</option>)}</select></label><button className="button button-primary" disabled={busy} onClick={()=>void store()}>Сохранить настройки</button></section>
 <section className="panel"><h2><Volume2 size={22}/> Озвучка</h2><p>Все основные сербские слова и примеры курса имеют предварительно сгенерированную звуковую дорожку. Базовый голос синтетический, не заменяет проверку произношения с носителем.</p><label className="form-label">Скорость воспроизведения<select className="form-control" value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="0.75">Медленно 0,75×</option><option value="1">Обычная 1×</option><option value="1.25">Быстрее 1,25×</option></select></label><button className="button button-secondary" onClick={()=>void play('Dobar dan!')}><Volume2 size={19}/> Проверить произношение</button><p className="tiny muted">Аудиофайл: {audioUrl('Dobar dan!')?'записан в проект':'нет файла'} · Состояние: {status}</p><div className="callout mint"><ShieldCheck size={22}/><div><b>Облачное хранение</b><p>Результаты сохраняются в Supabase. Ты можешь продолжить занятия после входа на другом устройстве.</p></div></div></section>
 <section className="panel"><h2><Cloud size={22}/> Данные и резервные копии</h2><p>Скачай облачную резервную копию своих уроков, карточек, экзаменов и настроек. Файл JSON пригоден для архивного хранения.</p><button className="button button-secondary fill" onClick={download}><Download size={19}/> Скачать облачный прогресс</button><div className="section-divider"/><h3>Перенести старый SrpskiLab</h3><p>Экспортируй `srpskilab_progress_v1` из старой версии. Перенесём историю, результаты экзаменов, словарь, карточки и сохранённые события. Импортированные уроки не будут считаться подтверждённым серверным зачётом.</p><label className="button button-secondary fill file-label"><Upload size={18}/> Выбрать старый JSON<input type="file" accept=".json,application/json" onChange={e=>void importFile(e)} hidden/></label><button className="button button-link" onClick={()=>void refresh()}>Обновить данные с сервера</button></section>
 <section className="panel"><h2><ShieldCheck size={22}/> Безопасность</h2><p className="muted">Текущий аккаунт: {user?.email||'—'}</p><h3><KeyRound size={18}/> Сменить пароль</h3><input type="password" className="form-control" autoComplete="new-password" value={password} placeholder="Новый пароль от 8 символов" onChange={e=>setPassword(e.target.value)}/><button disabled={busy||password.length<8} className="button button-secondary" onClick={()=>void changePassword()}>Изменить пароль</button><div className="section-divider"/><h3><Mail size={18}/> Сброс пароля по почте</h3><Link to="/auth/forgot-password">Получить ссылку для восстановления →</Link><div className="section-divider"/><h3><Trash2 size={18}/> Удалить аккаунт</h3><p>Необратимо удаляет профиль и историю на сервере. Сначала скачай резервную копию.</p><button disabled={busy} className="button button-danger" onClick={()=>void deleteAccount()}><AlertTriangle size={17}/> Удалить аккаунт</button></section></div>
 {message&&<div className="form-success" role="status">{message}</div>}{error&&<div className="form-error" role="alert">{error}</div>}
 <div className="callout"><ShieldCheck size={22}/><div><b>Приватность данных</b><p>К чужим результатам доступа нет: Supabase использует RLS, а завершение урока подтверждается серверной функцией.</p></div></div>
 </>;
}
